//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAT.Website
{
	/// <summary>
    /// This is the default class for the MAT website.
    /// </summary>
	public partial class _Default
	{
		/// <summary>
    	/// This is the default form for the MAT website.
    	/// </summary>
		protected System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
