CREATE TABLE [dbo].[paquetesPublic] (
    [Id]                           INT           IDENTITY (1, 1) NOT NULL,
    [PaqueteId]                    VARCHAR (255) NOT NULL,
    [PaqueteNombre]                VARCHAR (255) NOT NULL,
    [ViajePrecioCama]              INT           NULL,
    [ViajePrecioSemiCama]          INT           NULL,
    [PaqueteServicios]             VARCHAR (MAX) NOT NULL,
    [PaqueteDestino]               VARCHAR (255) NOT NULL,
    [ViajePrecioPromocional]       VARCHAR (255) NULL,
    [ViajeVencimientoPromocion]    VARCHAR (255) NULL,
    [ViajeNroDias]                 INT           NOT NULL,
    [ViajeNroNoches]               INT           NOT NULL,
    [ViajeFechaSalida]             DATETIME      NULL,
    [ViajeHoraSalida]              VARCHAR (255) NOT NULL,
    [ViajeFechaRegreso]            DATETIME      NOT NULL,
    [ViajeHoraRegreso]             VARCHAR (255) NOT NULL,
    [ViajeMedio]                   VARCHAR (255) NOT NULL,
    [ViajeDescripcion]             VARCHAR (255) NOT NULL,
    [PaqueteHoteles]               VARCHAR (255) NOT NULL,
    [ImagePrincipal]               VARCHAR (255) NULL,
    [LastUpdate]                   DATETIME      NOT NULL,
    [slug]                         VARCHAR (255) NOT NULL,
    [estado]                       BIT           NOT NULL,
    [created_at]                   DATETIME      NULL,
    [updated_at]                   DATETIME      NULL,
    [PaqueteExcursionesIncluidas]  VARCHAR (MAX) NOT NULL,
    [PaqueteExcursionesOpcionales] VARCHAR (MAX) NOT NULL,
    [MonedaTipoId]                 INT           NOT NULL,
    [PaqueteHotelesId]             VARCHAR (255) NULL,
    [PaqueteModePublicity]         BIT           NULL,
    CONSTRAINT [PK_paquetesPublic] PRIMARY KEY CLUSTERED ([Id] ASC)
);

