CREATE TABLE [dbo].[Viaje] (
    [ViajeID]             UNIQUEIDENTIFIER CONSTRAINT [DF_Viaje_ViajeID] DEFAULT (newid()) NOT NULL,
    [PaqueteID]           UNIQUEIDENTIFIER NULL,
    [Origen]              VARCHAR (50)     NULL,
    [FechaSalida]         DATE             NULL,
    [HoraSalida]          VARCHAR (50)     NULL,
    [PaisOrigen]          VARCHAR (50)     NULL,
    [PaisDestino]         VARCHAR (50)     NULL,
    [Paso]                VARCHAR (50)     NULL,
    [Medio]               VARCHAR (50)     NULL,
    [BusID]               UNIQUEIDENTIFIER NULL,
    [FechaRegreso]        DATE             NULL,
    [HoraRegreso]         VARCHAR (50)     NULL,
    [Descripcion]         VARCHAR (200)    NULL,
    [PrecioSemicama]      FLOAT (53)       NULL,
    [PrecioCama]          FLOAT (53)       NULL,
    [PrecioPromocional]   FLOAT (53)       NULL,
    [FechaPromocion]      DATETIME         NULL,
    [nDias]               INT              NULL,
    [nNoches]             INT              NULL,
    [TiempoConsentracion] INT              NULL,
    [Observaciones]       VARCHAR (500)    NULL,
    [MonedaTipo]          INT              CONSTRAINT [DF_Viaje_MonedaTipo] DEFAULT ((1)) NOT NULL,
    [IsPublicWeb]         BIT              NOT NULL,
    CONSTRAINT [DF_Viaje_IsPublicWeb DEFAULT 1, 
    CONSTRAINT [PK_Viaje] PRIMARY KEY CLUSTERED ([ViajeID] ASC),
    CONSTRAINT [FK_Viaje_Paquete] FOREIGN KEY ([PaqueteID]) REFERENCES [dbo].[Paquete] ([PaqueteID]),
    CONSTRAINT [FK_Viaje_Transporte] FOREIGN KEY ([BusID]) REFERENCES [dbo].[Transporte] ([TransporteID])
);

