
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Cliente.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using MAT.Entities.Validation;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'Cliente' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ClienteBase : EntityBase, ICliente, IEntityId<ClienteKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ClienteEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ClienteEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ClienteEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Cliente> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClienteEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClienteEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ClienteBase"/> instance.
		///</summary>
		public ClienteBase()
		{
			this.entityData = new ClienteEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ClienteBase"/> instance.
		///</summary>
		///<param name="_clienteId"></param>
		///<param name="_razonSocial"></param>
		///<param name="_cuit"></param>
		///<param name="_moneda"></param>
		///<param name="_empresa"></param>
		///<param name="_ocupacion"></param>
		///<param name="_formaPago"></param>
		///<param name="_condicionIva"></param>
		///<param name="_vendedorId"></param>
		///<param name="_fax"></param>
		///<param name="_web"></param>
		///<param name="_idioma"></param>
		///<param name="_promotor"></param>
		///<param name="_observacion"></param>
		///<param name="_tipoId"></param>
		public ClienteBase(System.Guid _clienteId, System.String _razonSocial, System.String _cuit, 
			System.String _moneda, System.String _empresa, System.String _ocupacion, System.Int32? _formaPago, 
			System.Int32? _condicionIva, System.Guid? _vendedorId, System.String _fax, System.String _web, 
			System.String _idioma, System.String _promotor, System.String _observacion, System.Int32 _tipoId)
		{
			this.entityData = new ClienteEntityData();
			this.backupData = null;

			this.ClienteId = _clienteId;
			this.RazonSocial = _razonSocial;
			this.Cuit = _cuit;
			this.Moneda = _moneda;
			this.Empresa = _empresa;
			this.Ocupacion = _ocupacion;
			this.FormaPago = _formaPago;
			this.CondicionIva = _condicionIva;
			this.VendedorId = _vendedorId;
			this.Fax = _fax;
			this.Web = _web;
			this.Idioma = _idioma;
			this.Promotor = _promotor;
			this.Observacion = _observacion;
			this.TipoId = _tipoId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Cliente"/> instance.
		///</summary>
		///<param name="_clienteId"></param>
		///<param name="_razonSocial"></param>
		///<param name="_cuit"></param>
		///<param name="_moneda"></param>
		///<param name="_empresa"></param>
		///<param name="_ocupacion"></param>
		///<param name="_formaPago"></param>
		///<param name="_condicionIva"></param>
		///<param name="_vendedorId"></param>
		///<param name="_fax"></param>
		///<param name="_web"></param>
		///<param name="_idioma"></param>
		///<param name="_promotor"></param>
		///<param name="_observacion"></param>
		///<param name="_tipoId"></param>
		public static Cliente CreateCliente(System.Guid _clienteId, System.String _razonSocial, System.String _cuit, 
			System.String _moneda, System.String _empresa, System.String _ocupacion, System.Int32? _formaPago, 
			System.Int32? _condicionIva, System.Guid? _vendedorId, System.String _fax, System.String _web, 
			System.String _idioma, System.String _promotor, System.String _observacion, System.Int32 _tipoId)
		{
			Cliente newCliente = new Cliente();
			newCliente.ClienteId = _clienteId;
			newCliente.RazonSocial = _razonSocial;
			newCliente.Cuit = _cuit;
			newCliente.Moneda = _moneda;
			newCliente.Empresa = _empresa;
			newCliente.Ocupacion = _ocupacion;
			newCliente.FormaPago = _formaPago;
			newCliente.CondicionIva = _condicionIva;
			newCliente.VendedorId = _vendedorId;
			newCliente.Fax = _fax;
			newCliente.Web = _web;
			newCliente.Idioma = _idioma;
			newCliente.Promotor = _promotor;
			newCliente.Observacion = _observacion;
			newCliente.TipoId = _tipoId;
			return newCliente;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ClienteId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "ClienteId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid ClienteId
		{
			get
			{
				return this.entityData.ClienteId; 
			}
			
			set
			{
				if (this.entityData.ClienteId == value)
					return;
				
                OnPropertyChanging("ClienteId");                    
				OnColumnChanging(ClienteColumn.ClienteId, this.entityData.ClienteId);
				this.entityData.ClienteId = value;
				this.EntityId.ClienteId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.ClienteId, this.entityData.ClienteId);
				OnPropertyChanged("ClienteId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ClienteID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ClienteID property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalClienteId
		{
			get { return this.entityData.OriginalClienteId; }
			set { this.entityData.OriginalClienteId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the RazonSocial property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String RazonSocial
		{
			get
			{
				return this.entityData.RazonSocial; 
			}
			
			set
			{
				if (this.entityData.RazonSocial == value)
					return;
				
                OnPropertyChanging("RazonSocial");                    
				OnColumnChanging(ClienteColumn.RazonSocial, this.entityData.RazonSocial);
				this.entityData.RazonSocial = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.RazonSocial, this.entityData.RazonSocial);
				OnPropertyChanged("RazonSocial");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Cuit property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Cuit
		{
			get
			{
				return this.entityData.Cuit; 
			}
			
			set
			{
				if (this.entityData.Cuit == value)
					return;
				
                OnPropertyChanging("Cuit");                    
				OnColumnChanging(ClienteColumn.Cuit, this.entityData.Cuit);
				this.entityData.Cuit = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Cuit, this.entityData.Cuit);
				OnPropertyChanged("Cuit");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Moneda property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Moneda
		{
			get
			{
				return this.entityData.Moneda; 
			}
			
			set
			{
				if (this.entityData.Moneda == value)
					return;
				
                OnPropertyChanging("Moneda");                    
				OnColumnChanging(ClienteColumn.Moneda, this.entityData.Moneda);
				this.entityData.Moneda = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Moneda, this.entityData.Moneda);
				OnPropertyChanged("Moneda");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Empresa property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Empresa
		{
			get
			{
				return this.entityData.Empresa; 
			}
			
			set
			{
				if (this.entityData.Empresa == value)
					return;
				
                OnPropertyChanging("Empresa");                    
				OnColumnChanging(ClienteColumn.Empresa, this.entityData.Empresa);
				this.entityData.Empresa = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Empresa, this.entityData.Empresa);
				OnPropertyChanged("Empresa");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ocupacion property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Ocupacion
		{
			get
			{
				return this.entityData.Ocupacion; 
			}
			
			set
			{
				if (this.entityData.Ocupacion == value)
					return;
				
                OnPropertyChanging("Ocupacion");                    
				OnColumnChanging(ClienteColumn.Ocupacion, this.entityData.Ocupacion);
				this.entityData.Ocupacion = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Ocupacion, this.entityData.Ocupacion);
				OnPropertyChanged("Ocupacion");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FormaPago property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsFormaPagoNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? FormaPago
		{
			get
			{
				return this.entityData.FormaPago; 
			}
			
			set
			{
				if (this.entityData.FormaPago == value)
					return;
				
                OnPropertyChanging("FormaPago");                    
				OnColumnChanging(ClienteColumn.FormaPago, this.entityData.FormaPago);
				this.entityData.FormaPago = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.FormaPago, this.entityData.FormaPago);
				OnPropertyChanged("FormaPago");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CondicionIva property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsCondicionIvaNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? CondicionIva
		{
			get
			{
				return this.entityData.CondicionIva; 
			}
			
			set
			{
				if (this.entityData.CondicionIva == value)
					return;
				
                OnPropertyChanging("CondicionIva");                    
				OnColumnChanging(ClienteColumn.CondicionIva, this.entityData.CondicionIva);
				this.entityData.CondicionIva = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.CondicionIva, this.entityData.CondicionIva);
				OnPropertyChanged("CondicionIva");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the VendedorId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return Guid.Empty. It is up to the developer
		/// to check the value of IsVendedorIdNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Guid? VendedorId
		{
			get
			{
				return this.entityData.VendedorId; 
			}
			
			set
			{
				if (this.entityData.VendedorId == value)
					return;
				
                OnPropertyChanging("VendedorId");                    
				OnColumnChanging(ClienteColumn.VendedorId, this.entityData.VendedorId);
				this.entityData.VendedorId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.VendedorId, this.entityData.VendedorId);
				OnPropertyChanged("VendedorId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Fax property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Fax
		{
			get
			{
				return this.entityData.Fax; 
			}
			
			set
			{
				if (this.entityData.Fax == value)
					return;
				
                OnPropertyChanging("Fax");                    
				OnColumnChanging(ClienteColumn.Fax, this.entityData.Fax);
				this.entityData.Fax = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Fax, this.entityData.Fax);
				OnPropertyChanged("Fax");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Web property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Web
		{
			get
			{
				return this.entityData.Web; 
			}
			
			set
			{
				if (this.entityData.Web == value)
					return;
				
                OnPropertyChanging("Web");                    
				OnColumnChanging(ClienteColumn.Web, this.entityData.Web);
				this.entityData.Web = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Web, this.entityData.Web);
				OnPropertyChanged("Web");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Idioma property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Idioma
		{
			get
			{
				return this.entityData.Idioma; 
			}
			
			set
			{
				if (this.entityData.Idioma == value)
					return;
				
                OnPropertyChanging("Idioma");                    
				OnColumnChanging(ClienteColumn.Idioma, this.entityData.Idioma);
				this.entityData.Idioma = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Idioma, this.entityData.Idioma);
				OnPropertyChanged("Idioma");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Promotor property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Promotor
		{
			get
			{
				return this.entityData.Promotor; 
			}
			
			set
			{
				if (this.entityData.Promotor == value)
					return;
				
                OnPropertyChanging("Promotor");                    
				OnColumnChanging(ClienteColumn.Promotor, this.entityData.Promotor);
				this.entityData.Promotor = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Promotor, this.entityData.Promotor);
				OnPropertyChanged("Promotor");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Observacion property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String Observacion
		{
			get
			{
				return this.entityData.Observacion; 
			}
			
			set
			{
				if (this.entityData.Observacion == value)
					return;
				
                OnPropertyChanging("Observacion");                    
				OnColumnChanging(ClienteColumn.Observacion, this.entityData.Observacion);
				this.entityData.Observacion = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.Observacion, this.entityData.Observacion);
				OnPropertyChanged("Observacion");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TipoId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "TipoId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 TipoId
		{
			get
			{
				return this.entityData.TipoId; 
			}
			
			set
			{
				if (this.entityData.TipoId == value)
					return;
				
                OnPropertyChanging("TipoId");                    
				OnColumnChanging(ClienteColumn.TipoId, this.entityData.TipoId);
				this.entityData.TipoId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClienteColumn.TipoId, this.entityData.TipoId);
				OnPropertyChanged("TipoId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Pago objects
		///	which are related to this object through the relation FK_Pago_Cliente
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Pago> PagoCollection
		{
			get { return entityData.PagoCollection; }
			set { entityData.PagoCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Nota objects
		///	which are related to this object through the relation FK_Nota_Cliente
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Nota> NotaCollection
		{
			get { return entityData.NotaCollection; }
			set { entityData.NotaCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of PasajeroMenor objects
		///	which are related to this object through the relation fk_cliente_menor
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<PasajeroMenor> PasajeroMenorCollectionGetByMenorid
		{
			get { return entityData.PasajeroMenorCollectionGetByMenorid; }
			set { entityData.PasajeroMenorCollectionGetByMenorid = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Factura objects
		///	which are related to this object through the relation FK_Factura_Cliente
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Factura> FacturaCollection
		{
			get { return entityData.FacturaCollection; }
			set { entityData.FacturaCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of PasajeroMenor objects
		///	which are related to this object through the relation fk_cliente_pasajero
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<PasajeroMenor> PasajeroMenorCollectionGetByPasajeroid
		{
			get { return entityData.PasajeroMenorCollectionGetByPasajeroid; }
			set { entityData.PasajeroMenorCollectionGetByPasajeroid = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Cuenta objects
		///	which are related to this object through the relation FK_Cuenta_Cliente
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Cuenta> CuentaCollection
		{
			get { return entityData.CuentaCollection; }
			set { entityData.CuentaCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of CuentaCorriente objects
		///	which are related to this object through the relation FK_CuentaCorriente_Cliente
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<CuentaCorriente> CuentaCorrienteCollection
		{
			get { return entityData.CuentaCorrienteCollection; }
			set { entityData.CuentaCorrienteCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("RazonSocial", "Razon Social", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Cuit", "Cuit", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Moneda", "Moneda", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Empresa", "Empresa", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Ocupacion", "Ocupacion", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Fax", "Fax", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Web", "Web", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Idioma", "Idioma", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Promotor", "Promotor", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Observacion", "Observacion", 250));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Cliente"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ClienteID", "RazonSocial", "Cuit", "Moneda", "Empresa", "Ocupacion", "FormaPago", "CondicionIva", "VendedorID", "Fax", "Web", "Idioma", "Promotor", "Observacion", "TipoID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ClienteEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Cliente) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Cliente>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Cliente);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Cliente Entity 
		///</summary>
		protected virtual Cliente Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Cliente copy = new Cliente();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ClienteId = this.ClienteId;
					copy.OriginalClienteId = this.OriginalClienteId;
				copy.RazonSocial = this.RazonSocial;
				copy.Cuit = this.Cuit;
				copy.Moneda = this.Moneda;
				copy.Empresa = this.Empresa;
				copy.Ocupacion = this.Ocupacion;
				copy.FormaPago = this.FormaPago;
				copy.CondicionIva = this.CondicionIva;
				copy.VendedorId = this.VendedorId;
				copy.Fax = this.Fax;
				copy.Web = this.Web;
				copy.Idioma = this.Idioma;
				copy.Promotor = this.Promotor;
				copy.Observacion = this.Observacion;
				copy.TipoId = this.TipoId;
			
		
			//deep copy nested objects
			copy.PagoCollection = (TList<Pago>) MakeCopyOf(this.PagoCollection, existingCopies); 
			copy.NotaCollection = (TList<Nota>) MakeCopyOf(this.NotaCollection, existingCopies); 
			copy.PasajeroMenorCollectionGetByMenorid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByMenorid, existingCopies); 
			copy.FacturaCollection = (TList<Factura>) MakeCopyOf(this.FacturaCollection, existingCopies); 
			copy.PasajeroMenorCollectionGetByPasajeroid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByPasajeroid, existingCopies); 
			copy.CuentaCollection = (TList<Cuenta>) MakeCopyOf(this.CuentaCollection, existingCopies); 
			copy.CuentaCorrienteCollection = (TList<CuentaCorriente>) MakeCopyOf(this.CuentaCorrienteCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Cliente Entity 
		///</summary>
		public virtual Cliente Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Cliente Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Cliente DeepCopy()
		{
			return EntityHelper.Clone<Cliente>(this as Cliente);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ClienteEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ClienteEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ClienteEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ClienteColumn column)
		{
			switch(column)
			{
					case ClienteColumn.ClienteId:
					return entityData.ClienteId != _originalData.ClienteId;
					case ClienteColumn.RazonSocial:
					return entityData.RazonSocial != _originalData.RazonSocial;
					case ClienteColumn.Cuit:
					return entityData.Cuit != _originalData.Cuit;
					case ClienteColumn.Moneda:
					return entityData.Moneda != _originalData.Moneda;
					case ClienteColumn.Empresa:
					return entityData.Empresa != _originalData.Empresa;
					case ClienteColumn.Ocupacion:
					return entityData.Ocupacion != _originalData.Ocupacion;
					case ClienteColumn.FormaPago:
					return entityData.FormaPago != _originalData.FormaPago;
					case ClienteColumn.CondicionIva:
					return entityData.CondicionIva != _originalData.CondicionIva;
					case ClienteColumn.VendedorId:
					return entityData.VendedorId != _originalData.VendedorId;
					case ClienteColumn.Fax:
					return entityData.Fax != _originalData.Fax;
					case ClienteColumn.Web:
					return entityData.Web != _originalData.Web;
					case ClienteColumn.Idioma:
					return entityData.Idioma != _originalData.Idioma;
					case ClienteColumn.Promotor:
					return entityData.Promotor != _originalData.Promotor;
					case ClienteColumn.Observacion:
					return entityData.Observacion != _originalData.Observacion;
					case ClienteColumn.TipoId:
					return entityData.TipoId != _originalData.TipoId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ClienteColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ClienteId != _originalData.ClienteId;
			result = result || entityData.RazonSocial != _originalData.RazonSocial;
			result = result || entityData.Cuit != _originalData.Cuit;
			result = result || entityData.Moneda != _originalData.Moneda;
			result = result || entityData.Empresa != _originalData.Empresa;
			result = result || entityData.Ocupacion != _originalData.Ocupacion;
			result = result || entityData.FormaPago != _originalData.FormaPago;
			result = result || entityData.CondicionIva != _originalData.CondicionIva;
			result = result || entityData.VendedorId != _originalData.VendedorId;
			result = result || entityData.Fax != _originalData.Fax;
			result = result || entityData.Web != _originalData.Web;
			result = result || entityData.Idioma != _originalData.Idioma;
			result = result || entityData.Promotor != _originalData.Promotor;
			result = result || entityData.Observacion != _originalData.Observacion;
			result = result || entityData.TipoId != _originalData.TipoId;
			return result;
		}	
		
		///<summary>
		///  Returns a Cliente Entity with the original data.
		///</summary>
		public Cliente GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCliente(
				_originalData.ClienteId,
				_originalData.RazonSocial,
				_originalData.Cuit,
				_originalData.Moneda,
				_originalData.Empresa,
				_originalData.Ocupacion,
				_originalData.FormaPago,
				_originalData.CondicionIva,
				_originalData.VendedorId,
				_originalData.Fax,
				_originalData.Web,
				_originalData.Idioma,
				_originalData.Promotor,
				_originalData.Observacion,
				_originalData.TipoId
				);
				
			return (Cliente)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ClienteBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ClienteBase)
				return ValueEquals(this, (ClienteBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ClienteBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ClienteId.GetHashCode() ^ 
					((this.RazonSocial == null) ? string.Empty : this.RazonSocial.ToString()).GetHashCode() ^ 
					((this.Cuit == null) ? string.Empty : this.Cuit.ToString()).GetHashCode() ^ 
					((this.Moneda == null) ? string.Empty : this.Moneda.ToString()).GetHashCode() ^ 
					((this.Empresa == null) ? string.Empty : this.Empresa.ToString()).GetHashCode() ^ 
					((this.Ocupacion == null) ? string.Empty : this.Ocupacion.ToString()).GetHashCode() ^ 
					((this.FormaPago == null) ? string.Empty : this.FormaPago.ToString()).GetHashCode() ^ 
					((this.CondicionIva == null) ? string.Empty : this.CondicionIva.ToString()).GetHashCode() ^ 
					((this.VendedorId == null) ? string.Empty : this.VendedorId.ToString()).GetHashCode() ^ 
					((this.Fax == null) ? string.Empty : this.Fax.ToString()).GetHashCode() ^ 
					((this.Web == null) ? string.Empty : this.Web.ToString()).GetHashCode() ^ 
					((this.Idioma == null) ? string.Empty : this.Idioma.ToString()).GetHashCode() ^ 
					((this.Promotor == null) ? string.Empty : this.Promotor.ToString()).GetHashCode() ^ 
					((this.Observacion == null) ? string.Empty : this.Observacion.ToString()).GetHashCode() ^ 
					this.TipoId.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ClienteBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ClienteBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ClienteBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ClienteBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ClienteBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ClienteBase Object1, ClienteBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ClienteId != Object2.ClienteId)
				equal = false;
			if ( Object1.RazonSocial != null && Object2.RazonSocial != null )
			{
				if (Object1.RazonSocial != Object2.RazonSocial)
					equal = false;
			}
			else if (Object1.RazonSocial == null ^ Object2.RazonSocial == null )
			{
				equal = false;
			}
			if ( Object1.Cuit != null && Object2.Cuit != null )
			{
				if (Object1.Cuit != Object2.Cuit)
					equal = false;
			}
			else if (Object1.Cuit == null ^ Object2.Cuit == null )
			{
				equal = false;
			}
			if ( Object1.Moneda != null && Object2.Moneda != null )
			{
				if (Object1.Moneda != Object2.Moneda)
					equal = false;
			}
			else if (Object1.Moneda == null ^ Object2.Moneda == null )
			{
				equal = false;
			}
			if ( Object1.Empresa != null && Object2.Empresa != null )
			{
				if (Object1.Empresa != Object2.Empresa)
					equal = false;
			}
			else if (Object1.Empresa == null ^ Object2.Empresa == null )
			{
				equal = false;
			}
			if ( Object1.Ocupacion != null && Object2.Ocupacion != null )
			{
				if (Object1.Ocupacion != Object2.Ocupacion)
					equal = false;
			}
			else if (Object1.Ocupacion == null ^ Object2.Ocupacion == null )
			{
				equal = false;
			}
			if ( Object1.FormaPago != null && Object2.FormaPago != null )
			{
				if (Object1.FormaPago != Object2.FormaPago)
					equal = false;
			}
			else if (Object1.FormaPago == null ^ Object2.FormaPago == null )
			{
				equal = false;
			}
			if ( Object1.CondicionIva != null && Object2.CondicionIva != null )
			{
				if (Object1.CondicionIva != Object2.CondicionIva)
					equal = false;
			}
			else if (Object1.CondicionIva == null ^ Object2.CondicionIva == null )
			{
				equal = false;
			}
			if ( Object1.VendedorId != null && Object2.VendedorId != null )
			{
				if (Object1.VendedorId != Object2.VendedorId)
					equal = false;
			}
			else if (Object1.VendedorId == null ^ Object2.VendedorId == null )
			{
				equal = false;
			}
			if ( Object1.Fax != null && Object2.Fax != null )
			{
				if (Object1.Fax != Object2.Fax)
					equal = false;
			}
			else if (Object1.Fax == null ^ Object2.Fax == null )
			{
				equal = false;
			}
			if ( Object1.Web != null && Object2.Web != null )
			{
				if (Object1.Web != Object2.Web)
					equal = false;
			}
			else if (Object1.Web == null ^ Object2.Web == null )
			{
				equal = false;
			}
			if ( Object1.Idioma != null && Object2.Idioma != null )
			{
				if (Object1.Idioma != Object2.Idioma)
					equal = false;
			}
			else if (Object1.Idioma == null ^ Object2.Idioma == null )
			{
				equal = false;
			}
			if ( Object1.Promotor != null && Object2.Promotor != null )
			{
				if (Object1.Promotor != Object2.Promotor)
					equal = false;
			}
			else if (Object1.Promotor == null ^ Object2.Promotor == null )
			{
				equal = false;
			}
			if ( Object1.Observacion != null && Object2.Observacion != null )
			{
				if (Object1.Observacion != Object2.Observacion)
					equal = false;
			}
			else if (Object1.Observacion == null ^ Object2.Observacion == null )
			{
				equal = false;
			}
			if (Object1.TipoId != Object2.TipoId)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ClienteBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ClienteComparer GetComparer()
        {
            return new ClienteComparer();
        }
        */

        // Comparer delegates back to Cliente
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Cliente rhs, ClienteColumn which)
        {
            switch (which)
            {
            	
            	
            	case ClienteColumn.ClienteId:
            		return this.ClienteId.CompareTo(rhs.ClienteId);
            		
            		                 
            	
            	
            	case ClienteColumn.RazonSocial:
            		return this.RazonSocial.CompareTo(rhs.RazonSocial);
            		
            		                 
            	
            	
            	case ClienteColumn.Cuit:
            		return this.Cuit.CompareTo(rhs.Cuit);
            		
            		                 
            	
            	
            	case ClienteColumn.Moneda:
            		return this.Moneda.CompareTo(rhs.Moneda);
            		
            		                 
            	
            	
            	case ClienteColumn.Empresa:
            		return this.Empresa.CompareTo(rhs.Empresa);
            		
            		                 
            	
            	
            	case ClienteColumn.Ocupacion:
            		return this.Ocupacion.CompareTo(rhs.Ocupacion);
            		
            		                 
            	
            	
            	case ClienteColumn.FormaPago:
            		return this.FormaPago.Value.CompareTo(rhs.FormaPago.Value);
            		
            		                 
            	
            	
            	case ClienteColumn.CondicionIva:
            		return this.CondicionIva.Value.CompareTo(rhs.CondicionIva.Value);
            		
            		                 
            	
            	
            	case ClienteColumn.VendedorId:
            		return this.VendedorId.Value.CompareTo(rhs.VendedorId.Value);
            		
            		                 
            	
            	
            	case ClienteColumn.Fax:
            		return this.Fax.CompareTo(rhs.Fax);
            		
            		                 
            	
            	
            	case ClienteColumn.Web:
            		return this.Web.CompareTo(rhs.Web);
            		
            		                 
            	
            	
            	case ClienteColumn.Idioma:
            		return this.Idioma.CompareTo(rhs.Idioma);
            		
            		                 
            	
            	
            	case ClienteColumn.Promotor:
            		return this.Promotor.CompareTo(rhs.Promotor);
            		
            		                 
            	
            	
            	case ClienteColumn.Observacion:
            		return this.Observacion.CompareTo(rhs.Observacion);
            		
            		                 
            	
            	
            	case ClienteColumn.TipoId:
            		return this.TipoId.CompareTo(rhs.TipoId);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ClienteKey> Members
		
		// member variable for the EntityId property
		private ClienteKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ClienteKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ClienteKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Cliente")
					.Append("|").Append( this.ClienteId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{16}{15}- ClienteId: {0}{15}- RazonSocial: {1}{15}- Cuit: {2}{15}- Moneda: {3}{15}- Empresa: {4}{15}- Ocupacion: {5}{15}- FormaPago: {6}{15}- CondicionIva: {7}{15}- VendedorId: {8}{15}- Fax: {9}{15}- Web: {10}{15}- Idioma: {11}{15}- Promotor: {12}{15}- Observacion: {13}{15}- TipoId: {14}{15}{17}", 
				this.ClienteId,
				(this.RazonSocial == null) ? string.Empty : this.RazonSocial.ToString(),
				(this.Cuit == null) ? string.Empty : this.Cuit.ToString(),
				(this.Moneda == null) ? string.Empty : this.Moneda.ToString(),
				(this.Empresa == null) ? string.Empty : this.Empresa.ToString(),
				(this.Ocupacion == null) ? string.Empty : this.Ocupacion.ToString(),
				(this.FormaPago == null) ? string.Empty : this.FormaPago.ToString(),
				(this.CondicionIva == null) ? string.Empty : this.CondicionIva.ToString(),
				(this.VendedorId == null) ? string.Empty : this.VendedorId.ToString(),
				(this.Fax == null) ? string.Empty : this.Fax.ToString(),
				(this.Web == null) ? string.Empty : this.Web.ToString(),
				(this.Idioma == null) ? string.Empty : this.Idioma.ToString(),
				(this.Promotor == null) ? string.Empty : this.Promotor.ToString(),
				(this.Observacion == null) ? string.Empty : this.Observacion.ToString(),
				this.TipoId,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Cliente' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ClienteEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ClienteID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Cliente"</remarks>
		public System.Guid ClienteId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalClienteId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// RazonSocial : 
		/// </summary>
		public System.String RazonSocial = null;
		
		/// <summary>
		/// Cuit : 
		/// </summary>
		public System.String Cuit = null;
		
		/// <summary>
		/// Moneda : 
		/// </summary>
		public System.String Moneda = null;
		
		/// <summary>
		/// Empresa : 
		/// </summary>
		public System.String Empresa = null;
		
		/// <summary>
		/// Ocupacion : 
		/// </summary>
		public System.String Ocupacion = null;
		
		/// <summary>
		/// FormaPago : 
		/// </summary>
		public System.Int32? FormaPago = null;
		
		/// <summary>
		/// CondicionIva : 
		/// </summary>
		public System.Int32? CondicionIva = null;
		
		/// <summary>
		/// VendedorID : 
		/// </summary>
		public System.Guid? VendedorId = null;
		
		/// <summary>
		/// Fax : 
		/// </summary>
		public System.String Fax = null;
		
		/// <summary>
		/// Web : 
		/// </summary>
		public System.String Web = null;
		
		/// <summary>
		/// Idioma : 
		/// </summary>
		public System.String Idioma = null;
		
		/// <summary>
		/// Promotor : 
		/// </summary>
		public System.String Promotor = null;
		
		/// <summary>
		/// Observacion : 
		/// </summary>
		public System.String Observacion = null;
		
		/// <summary>
		/// TipoID : 
		/// </summary>
		public System.Int32 TipoId = (int)0;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region PagoCollection
		
		private TList<Pago> _pagoClienteId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pagoClienteId
		/// </summary>
		
		public TList<Pago> PagoCollection
		{
			get
			{
				if (_pagoClienteId == null)
				{
				_pagoClienteId = new TList<Pago>();
				}
	
				return _pagoClienteId;
			}
			set { _pagoClienteId = value; }
		}
		
		#endregion

		#region NotaCollection
		
		private TList<Nota> _notaClienteId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _notaClienteId
		/// </summary>
		
		public TList<Nota> NotaCollection
		{
			get
			{
				if (_notaClienteId == null)
				{
				_notaClienteId = new TList<Nota>();
				}
	
				return _notaClienteId;
			}
			set { _notaClienteId = value; }
		}
		
		#endregion

		#region PasajeroMenorCollectionGetByMenorid
		
		private TList<PasajeroMenor> _pasajeroMenorPasajeroidGetByMenorid;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pasajeroMenorPasajeroidGetByMenorid
		/// </summary>
		
		public TList<PasajeroMenor> PasajeroMenorCollectionGetByMenorid
		{
			get
			{
				if (_pasajeroMenorPasajeroidGetByMenorid == null)
				{
				_pasajeroMenorPasajeroidGetByMenorid = new TList<PasajeroMenor>();
				}
	
				return _pasajeroMenorPasajeroidGetByMenorid;
			}
			set { _pasajeroMenorPasajeroidGetByMenorid = value; }
		}
		
		#endregion

		#region FacturaCollection
		
		private TList<Factura> _facturaClienteId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _facturaClienteId
		/// </summary>
		
		public TList<Factura> FacturaCollection
		{
			get
			{
				if (_facturaClienteId == null)
				{
				_facturaClienteId = new TList<Factura>();
				}
	
				return _facturaClienteId;
			}
			set { _facturaClienteId = value; }
		}
		
		#endregion

		#region PasajeroMenorCollectionGetByPasajeroid
		
		private TList<PasajeroMenor> _pasajeroMenorPasajeroidGetByPasajeroid;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pasajeroMenorPasajeroidGetByPasajeroid
		/// </summary>
		
		public TList<PasajeroMenor> PasajeroMenorCollectionGetByPasajeroid
		{
			get
			{
				if (_pasajeroMenorPasajeroidGetByPasajeroid == null)
				{
				_pasajeroMenorPasajeroidGetByPasajeroid = new TList<PasajeroMenor>();
				}
	
				return _pasajeroMenorPasajeroidGetByPasajeroid;
			}
			set { _pasajeroMenorPasajeroidGetByPasajeroid = value; }
		}
		
		#endregion

		#region CuentaCollection
		
		private TList<Cuenta> _cuentaClienteId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _cuentaClienteId
		/// </summary>
		
		public TList<Cuenta> CuentaCollection
		{
			get
			{
				if (_cuentaClienteId == null)
				{
				_cuentaClienteId = new TList<Cuenta>();
				}
	
				return _cuentaClienteId;
			}
			set { _cuentaClienteId = value; }
		}
		
		#endregion

		#region CuentaCorrienteCollection
		
		private TList<CuentaCorriente> _cuentaCorrienteClienteId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _cuentaCorrienteClienteId
		/// </summary>
		
		public TList<CuentaCorriente> CuentaCorrienteCollection
		{
			get
			{
				if (_cuentaCorrienteClienteId == null)
				{
				_cuentaCorrienteClienteId = new TList<CuentaCorriente>();
				}
	
				return _cuentaCorrienteClienteId;
			}
			set { _cuentaCorrienteClienteId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ClienteEntityData _tmp = new ClienteEntityData();
						
			_tmp.ClienteId = this.ClienteId;
			_tmp.OriginalClienteId = this.OriginalClienteId;
			
			_tmp.RazonSocial = this.RazonSocial;
			_tmp.Cuit = this.Cuit;
			_tmp.Moneda = this.Moneda;
			_tmp.Empresa = this.Empresa;
			_tmp.Ocupacion = this.Ocupacion;
			_tmp.FormaPago = this.FormaPago;
			_tmp.CondicionIva = this.CondicionIva;
			_tmp.VendedorId = this.VendedorId;
			_tmp.Fax = this.Fax;
			_tmp.Web = this.Web;
			_tmp.Idioma = this.Idioma;
			_tmp.Promotor = this.Promotor;
			_tmp.Observacion = this.Observacion;
			_tmp.TipoId = this.TipoId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._pagoClienteId != null)
				_tmp.PagoCollection = (TList<Pago>) MakeCopyOf(this.PagoCollection); 
			if (this._notaClienteId != null)
				_tmp.NotaCollection = (TList<Nota>) MakeCopyOf(this.NotaCollection); 
			if (this._pasajeroMenorPasajeroidGetByMenorid != null)
				_tmp.PasajeroMenorCollectionGetByMenorid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByMenorid); 
			if (this._facturaClienteId != null)
				_tmp.FacturaCollection = (TList<Factura>) MakeCopyOf(this.FacturaCollection); 
			if (this._pasajeroMenorPasajeroidGetByPasajeroid != null)
				_tmp.PasajeroMenorCollectionGetByPasajeroid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByPasajeroid); 
			if (this._cuentaClienteId != null)
				_tmp.CuentaCollection = (TList<Cuenta>) MakeCopyOf(this.CuentaCollection); 
			if (this._cuentaCorrienteClienteId != null)
				_tmp.CuentaCorrienteCollection = (TList<CuentaCorriente>) MakeCopyOf(this.CuentaCorrienteCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ClienteEntityData _tmp = new ClienteEntityData();
						
			_tmp.ClienteId = this.ClienteId;
			_tmp.OriginalClienteId = this.OriginalClienteId;
			
			_tmp.RazonSocial = this.RazonSocial;
			_tmp.Cuit = this.Cuit;
			_tmp.Moneda = this.Moneda;
			_tmp.Empresa = this.Empresa;
			_tmp.Ocupacion = this.Ocupacion;
			_tmp.FormaPago = this.FormaPago;
			_tmp.CondicionIva = this.CondicionIva;
			_tmp.VendedorId = this.VendedorId;
			_tmp.Fax = this.Fax;
			_tmp.Web = this.Web;
			_tmp.Idioma = this.Idioma;
			_tmp.Promotor = this.Promotor;
			_tmp.Observacion = this.Observacion;
			_tmp.TipoId = this.TipoId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.PagoCollection = (TList<Pago>) MakeCopyOf(this.PagoCollection, existingCopies); 
			_tmp.NotaCollection = (TList<Nota>) MakeCopyOf(this.NotaCollection, existingCopies); 
			_tmp.PasajeroMenorCollectionGetByMenorid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByMenorid, existingCopies); 
			_tmp.FacturaCollection = (TList<Factura>) MakeCopyOf(this.FacturaCollection, existingCopies); 
			_tmp.PasajeroMenorCollectionGetByPasajeroid = (TList<PasajeroMenor>) MakeCopyOf(this.PasajeroMenorCollectionGetByPasajeroid, existingCopies); 
			_tmp.CuentaCollection = (TList<Cuenta>) MakeCopyOf(this.CuentaCollection, existingCopies); 
			_tmp.CuentaCorrienteCollection = (TList<CuentaCorriente>) MakeCopyOf(this.CuentaCorrienteCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClienteColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ClienteColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClienteColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ClienteColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClienteColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ClienteColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				ClienteEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ClienteEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClienteColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ClienteColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ClienteEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ClienteEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ClienteEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Cliente"/> object.
	/// </remarks>
	public class ClienteEventArgs : System.EventArgs
	{
		private ClienteColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ClienteEventArgs class.
		///</summary>
		public ClienteEventArgs(ClienteColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ClienteEventArgs class.
		///</summary>
		public ClienteEventArgs(ClienteColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ClienteColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ClienteColumn" />
		public ClienteColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Cliente related events.
	///</summary>
	public delegate void ClienteEventHandler(object sender, ClienteEventArgs e);
	
	#region ClienteComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ClienteComparer : System.Collections.Generic.IComparer<Cliente>
	{
		ClienteColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ClienteComparer"/> class.
        /// </summary>
		public ClienteComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ClienteComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ClienteComparer(ClienteColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Cliente"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Cliente"/> to compare.</param>
        /// <param name="b">The second <c>Cliente</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Cliente a, Cliente b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Cliente entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Cliente a, Cliente b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ClienteColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ClienteKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Cliente"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ClienteKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ClienteKey class.
		/// </summary>
		public ClienteKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ClienteKey class.
		/// </summary>
		public ClienteKey(ClienteBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ClienteId = entity.ClienteId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ClienteKey class.
		/// </summary>
		public ClienteKey(System.Guid _clienteId)
		{
			#region Init Properties

			this.ClienteId = _clienteId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ClienteBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ClienteBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ClienteId property
		private System.Guid _clienteId;
		
		/// <summary>
		/// Gets or sets the ClienteId property.
		/// </summary>
		public System.Guid ClienteId
		{
			get { return _clienteId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ClienteId = value;
				
				_clienteId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ClienteId = ( values["ClienteId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["ClienteId"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ClienteId", ClienteId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ClienteId: {0}{1}",
								ClienteId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ClienteColumn Enum
	
	/// <summary>
	/// Enumerate the Cliente columns.
	/// </summary>
	[Serializable]
	public enum ClienteColumn : int
	{
		/// <summary>
		/// ClienteId : 
		/// </summary>
		[EnumTextValue("ClienteID")]
		[ColumnEnum("ClienteID", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		ClienteId = 1,
		/// <summary>
		/// RazonSocial : 
		/// </summary>
		[EnumTextValue("RazonSocial")]
		[ColumnEnum("RazonSocial", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		RazonSocial = 2,
		/// <summary>
		/// Cuit : 
		/// </summary>
		[EnumTextValue("Cuit")]
		[ColumnEnum("Cuit", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Cuit = 3,
		/// <summary>
		/// Moneda : 
		/// </summary>
		[EnumTextValue("Moneda")]
		[ColumnEnum("Moneda", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Moneda = 4,
		/// <summary>
		/// Empresa : 
		/// </summary>
		[EnumTextValue("Empresa")]
		[ColumnEnum("Empresa", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Empresa = 5,
		/// <summary>
		/// Ocupacion : 
		/// </summary>
		[EnumTextValue("Ocupacion")]
		[ColumnEnum("Ocupacion", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Ocupacion = 6,
		/// <summary>
		/// FormaPago : 
		/// </summary>
		[EnumTextValue("FormaPago")]
		[ColumnEnum("FormaPago", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		FormaPago = 7,
		/// <summary>
		/// CondicionIva : 
		/// </summary>
		[EnumTextValue("CondicionIva")]
		[ColumnEnum("CondicionIva", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CondicionIva = 8,
		/// <summary>
		/// VendedorId : 
		/// </summary>
		[EnumTextValue("VendedorID")]
		[ColumnEnum("VendedorID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
		VendedorId = 9,
		/// <summary>
		/// Fax : 
		/// </summary>
		[EnumTextValue("Fax")]
		[ColumnEnum("Fax", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Fax = 10,
		/// <summary>
		/// Web : 
		/// </summary>
		[EnumTextValue("Web")]
		[ColumnEnum("Web", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Web = 11,
		/// <summary>
		/// Idioma : 
		/// </summary>
		[EnumTextValue("Idioma")]
		[ColumnEnum("Idioma", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Idioma = 12,
		/// <summary>
		/// Promotor : 
		/// </summary>
		[EnumTextValue("Promotor")]
		[ColumnEnum("Promotor", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Promotor = 13,
		/// <summary>
		/// Observacion : 
		/// </summary>
		[EnumTextValue("Observacion")]
		[ColumnEnum("Observacion", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 250)]
		Observacion = 14,
		/// <summary>
		/// TipoId : 
		/// </summary>
		[EnumTextValue("TipoID")]
		[ColumnEnum("TipoID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		TipoId = 15
	}//End enum

	#endregion ClienteColumn Enum

} // end namespace
