using System;
using System.ComponentModel;

namespace MAT.Entities
{
	/// <summary>
	///		The data structure representation of the 'Ciudad' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICiudad 
	{
		/// <summary>			
		/// CiudadID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Ciudad"</remarks>
		System.Int32 CiudadId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalCiudadId { get; set; }
			
		
		
		/// <summary>
		/// CiudadNombre : 
		/// </summary>
		System.String  CiudadNombre  { get; set; }
		
		/// <summary>
		/// PaisCodigo : 
		/// </summary>
		System.String  PaisCodigo  { get; set; }
		
		/// <summary>
		/// CiudadDistrito : 
		/// </summary>
		System.String  CiudadDistrito  { get; set; }
		
		/// <summary>
		/// CiudadPoblacion : 
		/// </summary>
		System.Int32  CiudadPoblacion  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


