using System;
using System.ComponentModel;

namespace MAT.Entities
{
	/// <summary>
	///		The data structure representation of the 'Cuenta' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICuenta 
	{
		/// <summary>			
		/// CuentaID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Cuenta"</remarks>
		System.Guid CuentaId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalCuentaId { get; set; }
			
		
		
		/// <summary>
		/// ClienteID : 
		/// </summary>
		System.Guid  ClienteId  { get; set; }
		
		/// <summary>
		/// Estado : 
		/// </summary>
		System.Boolean  Estado  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _movimientoCuentaCuentaId
		/// </summary>	
		TList<MovimientoCuenta> MovimientoCuentaCollection {  get;  set;}	

		#endregion Data Properties

	}
}


