using System;
using System.ComponentModel;

namespace MAT.Entities
{
	/// <summary>
	///		The data structure representation of the 'Excursion' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IExcursion 
	{
		/// <summary>			
		/// ExcursionID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Excursion"</remarks>
		System.Guid ExcursionId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalExcursionId { get; set; }
			
		
		
		/// <summary>
		/// Descripcion : 
		/// </summary>
		System.String  Descripcion  { get; set; }
		
		/// <summary>
		/// Costo : 
		/// </summary>
		System.Double?  Costo  { get; set; }
		
		/// <summary>
		/// Observaciones : 
		/// </summary>
		System.String  Observaciones  { get; set; }
		
		/// <summary>
		/// ProveedorID : 
		/// </summary>
		System.Guid?  ProveedorId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _paqueteExcursionExcursionId
		/// </summary>	
		TList<PaqueteExcursion> PaqueteExcursionCollection {  get;  set;}	

		#endregion Data Properties

	}
}


