using System;
using System.ComponentModel;

namespace MAT.Entities
{
	/// <summary>
	///		The data structure representation of the 'PlanillaServicio' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPlanillaServicio 
	{
		/// <summary>			
		/// PlanillaServicioID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PlanillaServicio"</remarks>
		System.Guid PlanillaServicioId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalPlanillaServicioId { get; set; }
			
		
		
		/// <summary>
		/// ViajeID : 
		/// </summary>
		System.Guid  ViajeId  { get; set; }
		
		/// <summary>
		/// FechaRegistro : 
		/// </summary>
		System.DateTime  FechaRegistro  { get; set; }
		
		/// <summary>
		/// Total : 
		/// </summary>
		System.Double  Total  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _planillaServicioItemPlanillaServicioId
		/// </summary>	
		TList<PlanillaServicioItem> PlanillaServicioItemCollection {  get;  set;}	

		#endregion Data Properties

	}
}


