using System;
using System.ComponentModel;

namespace MAT.Entities
{
	/// <summary>
	///		The data structure representation of the 'Proveedor' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IProveedor 
	{
		/// <summary>			
		/// ProveedorID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Proveedor"</remarks>
		System.Guid ProveedorId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalProveedorId { get; set; }
			
		
		
		/// <summary>
		/// RazonSocial : 
		/// </summary>
		System.String  RazonSocial  { get; set; }
		
		/// <summary>
		/// Telefono : 
		/// </summary>
		System.String  Telefono  { get; set; }
		
		/// <summary>
		/// Fax : 
		/// </summary>
		System.String  Fax  { get; set; }
		
		/// <summary>
		/// Web : 
		/// </summary>
		System.String  Web  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Idioma : 
		/// </summary>
		System.String  Idioma  { get; set; }
		
		/// <summary>
		/// CondicionIva : 
		/// </summary>
		System.Int32?  CondicionIva  { get; set; }
		
		/// <summary>
		/// Cuit : 
		/// </summary>
		System.String  Cuit  { get; set; }
		
		/// <summary>
		/// FormaPago : 
		/// </summary>
		System.Int32?  FormaPago  { get; set; }
		
		/// <summary>
		/// LocalidadID : 
		/// </summary>
		System.Int32?  LocalidadId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _servicioProveedorId
		/// </summary>	
		TList<Servicio> ServicioCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _excursionProveedorId
		/// </summary>	
		TList<Excursion> ExcursionCollection {  get;  set;}	

		#endregion Data Properties

	}
}


