
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PasajeAdicional.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using MAT.Entities.Validation;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'PasajeAdicional' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PasajeAdicionalBase : EntityBase, IPasajeAdicional, IEntityId<PasajeAdicionalKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PasajeAdicionalEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PasajeAdicionalEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PasajeAdicionalEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PasajeAdicional> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PasajeAdicionalEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PasajeAdicionalEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PasajeAdicionalBase"/> instance.
		///</summary>
		public PasajeAdicionalBase()
		{
			this.entityData = new PasajeAdicionalEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PasajeAdicionalBase"/> instance.
		///</summary>
		///<param name="_pasajeAdicionalId"></param>
		///<param name="_pasajeId"></param>
		///<param name="_adicionalId"></param>
		public PasajeAdicionalBase(System.Guid _pasajeAdicionalId, System.Guid? _pasajeId, 
			System.Guid? _adicionalId)
		{
			this.entityData = new PasajeAdicionalEntityData();
			this.backupData = null;

			this.PasajeAdicionalId = _pasajeAdicionalId;
			this.PasajeId = _pasajeId;
			this.AdicionalId = _adicionalId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PasajeAdicional"/> instance.
		///</summary>
		///<param name="_pasajeAdicionalId"></param>
		///<param name="_pasajeId"></param>
		///<param name="_adicionalId"></param>
		public static PasajeAdicional CreatePasajeAdicional(System.Guid _pasajeAdicionalId, System.Guid? _pasajeId, 
			System.Guid? _adicionalId)
		{
			PasajeAdicional newPasajeAdicional = new PasajeAdicional();
			newPasajeAdicional.PasajeAdicionalId = _pasajeAdicionalId;
			newPasajeAdicional.PasajeId = _pasajeId;
			newPasajeAdicional.AdicionalId = _adicionalId;
			return newPasajeAdicional;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the PasajeAdicionalId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "PasajeAdicionalId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid PasajeAdicionalId
		{
			get
			{
				return this.entityData.PasajeAdicionalId; 
			}
			
			set
			{
				if (this.entityData.PasajeAdicionalId == value)
					return;
				
                OnPropertyChanging("PasajeAdicionalId");                    
				OnColumnChanging(PasajeAdicionalColumn.PasajeAdicionalId, this.entityData.PasajeAdicionalId);
				this.entityData.PasajeAdicionalId = value;
				this.EntityId.PasajeAdicionalId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeAdicionalColumn.PasajeAdicionalId, this.entityData.PasajeAdicionalId);
				OnPropertyChanged("PasajeAdicionalId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the PasajeAdicionalID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the PasajeAdicionalID property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalPasajeAdicionalId
		{
			get { return this.entityData.OriginalPasajeAdicionalId; }
			set { this.entityData.OriginalPasajeAdicionalId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the PasajeId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return Guid.Empty. It is up to the developer
		/// to check the value of IsPasajeIdNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Guid? PasajeId
		{
			get
			{
				return this.entityData.PasajeId; 
			}
			
			set
			{
				if (this.entityData.PasajeId == value)
					return;
				
                OnPropertyChanging("PasajeId");                    
				OnColumnChanging(PasajeAdicionalColumn.PasajeId, this.entityData.PasajeId);
				this.entityData.PasajeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeAdicionalColumn.PasajeId, this.entityData.PasajeId);
				OnPropertyChanged("PasajeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AdicionalId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return Guid.Empty. It is up to the developer
		/// to check the value of IsAdicionalIdNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Guid? AdicionalId
		{
			get
			{
				return this.entityData.AdicionalId; 
			}
			
			set
			{
				if (this.entityData.AdicionalId == value)
					return;
				
                OnPropertyChanging("AdicionalId");                    
				OnColumnChanging(PasajeAdicionalColumn.AdicionalId, this.entityData.AdicionalId);
				this.entityData.AdicionalId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeAdicionalColumn.AdicionalId, this.entityData.AdicionalId);
				OnPropertyChanged("AdicionalId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Adicional"/>.
		/// </summary>
		/// <value>The source Adicional for AdicionalId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Adicional AdicionalIdSource
      	{
            get { return entityData.AdicionalIdSource; }
            set { entityData.AdicionalIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Pasaje"/>.
		/// </summary>
		/// <value>The source Pasaje for PasajeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Pasaje PasajeIdSource
      	{
            get { return entityData.PasajeIdSource; }
            set { entityData.PasajeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PasajeAdicional"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"PasajeAdicionalID", "PasajeID", "AdicionalID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PasajeAdicionalEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PasajeAdicional) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PasajeAdicional>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PasajeAdicional);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PasajeAdicional Entity 
		///</summary>
		protected virtual PasajeAdicional Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			PasajeAdicional copy = new PasajeAdicional();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.PasajeAdicionalId = this.PasajeAdicionalId;
					copy.OriginalPasajeAdicionalId = this.OriginalPasajeAdicionalId;
				copy.PasajeId = this.PasajeId;
				copy.AdicionalId = this.AdicionalId;
			
			if (this.AdicionalIdSource != null && existingCopies.Contains(this.AdicionalIdSource))
				copy.AdicionalIdSource = existingCopies[this.AdicionalIdSource] as Adicional;
			else
				copy.AdicionalIdSource = MakeCopyOf(this.AdicionalIdSource, existingCopies) as Adicional;
			if (this.PasajeIdSource != null && existingCopies.Contains(this.PasajeIdSource))
				copy.PasajeIdSource = existingCopies[this.PasajeIdSource] as Pasaje;
			else
				copy.PasajeIdSource = MakeCopyOf(this.PasajeIdSource, existingCopies) as Pasaje;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed PasajeAdicional Entity 
		///</summary>
		public virtual PasajeAdicional Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed PasajeAdicional Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PasajeAdicional DeepCopy()
		{
			return EntityHelper.Clone<PasajeAdicional>(this as PasajeAdicional);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PasajeAdicionalEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PasajeAdicionalEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PasajeAdicionalEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PasajeAdicionalColumn column)
		{
			switch(column)
			{
					case PasajeAdicionalColumn.PasajeAdicionalId:
					return entityData.PasajeAdicionalId != _originalData.PasajeAdicionalId;
					case PasajeAdicionalColumn.PasajeId:
					return entityData.PasajeId != _originalData.PasajeId;
					case PasajeAdicionalColumn.AdicionalId:
					return entityData.AdicionalId != _originalData.AdicionalId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PasajeAdicionalColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.PasajeAdicionalId != _originalData.PasajeAdicionalId;
			result = result || entityData.PasajeId != _originalData.PasajeId;
			result = result || entityData.AdicionalId != _originalData.AdicionalId;
			return result;
		}	
		
		///<summary>
		///  Returns a PasajeAdicional Entity with the original data.
		///</summary>
		public PasajeAdicional GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePasajeAdicional(
				_originalData.PasajeAdicionalId,
				_originalData.PasajeId,
				_originalData.AdicionalId
				);
				
			return (PasajeAdicional)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PasajeAdicionalBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PasajeAdicionalBase)
				return ValueEquals(this, (PasajeAdicionalBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PasajeAdicionalBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.PasajeAdicionalId.GetHashCode() ^ 
					((this.PasajeId == null) ? string.Empty : this.PasajeId.ToString()).GetHashCode() ^ 
					((this.AdicionalId == null) ? string.Empty : this.AdicionalId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PasajeAdicionalBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PasajeAdicionalBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PasajeAdicionalBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PasajeAdicionalBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PasajeAdicionalBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PasajeAdicionalBase Object1, PasajeAdicionalBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.PasajeAdicionalId != Object2.PasajeAdicionalId)
				equal = false;
			if ( Object1.PasajeId != null && Object2.PasajeId != null )
			{
				if (Object1.PasajeId != Object2.PasajeId)
					equal = false;
			}
			else if (Object1.PasajeId == null ^ Object2.PasajeId == null )
			{
				equal = false;
			}
			if ( Object1.AdicionalId != null && Object2.AdicionalId != null )
			{
				if (Object1.AdicionalId != Object2.AdicionalId)
					equal = false;
			}
			else if (Object1.AdicionalId == null ^ Object2.AdicionalId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PasajeAdicionalBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PasajeAdicionalComparer GetComparer()
        {
            return new PasajeAdicionalComparer();
        }
        */

        // Comparer delegates back to PasajeAdicional
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PasajeAdicional rhs, PasajeAdicionalColumn which)
        {
            switch (which)
            {
            	
            	
            	case PasajeAdicionalColumn.PasajeAdicionalId:
            		return this.PasajeAdicionalId.CompareTo(rhs.PasajeAdicionalId);
            		
            		                 
            	
            	
            	case PasajeAdicionalColumn.PasajeId:
            		return this.PasajeId.Value.CompareTo(rhs.PasajeId.Value);
            		
            		                 
            	
            	
            	case PasajeAdicionalColumn.AdicionalId:
            		return this.AdicionalId.Value.CompareTo(rhs.AdicionalId.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PasajeAdicionalKey> Members
		
		// member variable for the EntityId property
		private PasajeAdicionalKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PasajeAdicionalKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PasajeAdicionalKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PasajeAdicional")
					.Append("|").Append( this.PasajeAdicionalId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- PasajeAdicionalId: {0}{3}- PasajeId: {1}{3}- AdicionalId: {2}{3}{5}", 
				this.PasajeAdicionalId,
				(this.PasajeId == null) ? string.Empty : this.PasajeId.ToString(),
				(this.AdicionalId == null) ? string.Empty : this.AdicionalId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PasajeAdicional' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PasajeAdicionalEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// PasajeAdicionalID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PasajeAdicional"</remarks>
		public System.Guid PasajeAdicionalId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalPasajeAdicionalId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// PasajeID : 
		/// </summary>
		public System.Guid? PasajeId = null;
		
		/// <summary>
		/// AdicionalID : 
		/// </summary>
		public System.Guid? AdicionalId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Adicional _adicionalIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Adicional"/>.
		/// </summary>
		/// <value>The source Adicional for AdicionalId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Adicional AdicionalIdSource
      	{
            get { return this._adicionalIdSource; }
            set { this._adicionalIdSource = value; }
      	}
		private Pasaje _pasajeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Pasaje"/>.
		/// </summary>
		/// <value>The source Pasaje for PasajeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Pasaje PasajeIdSource
      	{
            get { return this._pasajeIdSource; }
            set { this._pasajeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PasajeAdicionalEntityData _tmp = new PasajeAdicionalEntityData();
						
			_tmp.PasajeAdicionalId = this.PasajeAdicionalId;
			_tmp.OriginalPasajeAdicionalId = this.OriginalPasajeAdicionalId;
			
			_tmp.PasajeId = this.PasajeId;
			_tmp.AdicionalId = this.AdicionalId;
			
			#region Source Parent Composite Entities
			if (this.AdicionalIdSource != null)
				_tmp.AdicionalIdSource = MakeCopyOf(this.AdicionalIdSource) as Adicional;
			if (this.PasajeIdSource != null)
				_tmp.PasajeIdSource = MakeCopyOf(this.PasajeIdSource) as Pasaje;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PasajeAdicionalEntityData _tmp = new PasajeAdicionalEntityData();
						
			_tmp.PasajeAdicionalId = this.PasajeAdicionalId;
			_tmp.OriginalPasajeAdicionalId = this.OriginalPasajeAdicionalId;
			
			_tmp.PasajeId = this.PasajeId;
			_tmp.AdicionalId = this.AdicionalId;
			
			#region Source Parent Composite Entities
			if (this.AdicionalIdSource != null && existingCopies.Contains(this.AdicionalIdSource))
				_tmp.AdicionalIdSource = existingCopies[this.AdicionalIdSource] as Adicional;
			else
				_tmp.AdicionalIdSource = MakeCopyOf(this.AdicionalIdSource, existingCopies) as Adicional;
			if (this.PasajeIdSource != null && existingCopies.Contains(this.PasajeIdSource))
				_tmp.PasajeIdSource = existingCopies[this.PasajeIdSource] as Pasaje;
			else
				_tmp.PasajeIdSource = MakeCopyOf(this.PasajeIdSource, existingCopies) as Pasaje;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeAdicionalColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PasajeAdicionalColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeAdicionalColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PasajeAdicionalColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeAdicionalColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PasajeAdicionalColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PasajeAdicionalEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PasajeAdicionalEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeAdicionalColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PasajeAdicionalColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PasajeAdicionalEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PasajeAdicionalEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PasajeAdicionalEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PasajeAdicional"/> object.
	/// </remarks>
	public class PasajeAdicionalEventArgs : System.EventArgs
	{
		private PasajeAdicionalColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PasajeAdicionalEventArgs class.
		///</summary>
		public PasajeAdicionalEventArgs(PasajeAdicionalColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PasajeAdicionalEventArgs class.
		///</summary>
		public PasajeAdicionalEventArgs(PasajeAdicionalColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PasajeAdicionalColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PasajeAdicionalColumn" />
		public PasajeAdicionalColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PasajeAdicional related events.
	///</summary>
	public delegate void PasajeAdicionalEventHandler(object sender, PasajeAdicionalEventArgs e);
	
	#region PasajeAdicionalComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PasajeAdicionalComparer : System.Collections.Generic.IComparer<PasajeAdicional>
	{
		PasajeAdicionalColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PasajeAdicionalComparer"/> class.
        /// </summary>
		public PasajeAdicionalComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PasajeAdicionalComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PasajeAdicionalComparer(PasajeAdicionalColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="PasajeAdicional"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="PasajeAdicional"/> to compare.</param>
        /// <param name="b">The second <c>PasajeAdicional</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PasajeAdicional a, PasajeAdicional b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PasajeAdicional entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PasajeAdicional a, PasajeAdicional b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PasajeAdicionalColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PasajeAdicionalKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PasajeAdicional"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PasajeAdicionalKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PasajeAdicionalKey class.
		/// </summary>
		public PasajeAdicionalKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PasajeAdicionalKey class.
		/// </summary>
		public PasajeAdicionalKey(PasajeAdicionalBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.PasajeAdicionalId = entity.PasajeAdicionalId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PasajeAdicionalKey class.
		/// </summary>
		public PasajeAdicionalKey(System.Guid _pasajeAdicionalId)
		{
			#region Init Properties

			this.PasajeAdicionalId = _pasajeAdicionalId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PasajeAdicionalBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PasajeAdicionalBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the PasajeAdicionalId property
		private System.Guid _pasajeAdicionalId;
		
		/// <summary>
		/// Gets or sets the PasajeAdicionalId property.
		/// </summary>
		public System.Guid PasajeAdicionalId
		{
			get { return _pasajeAdicionalId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.PasajeAdicionalId = value;
				
				_pasajeAdicionalId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				PasajeAdicionalId = ( values["PasajeAdicionalId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["PasajeAdicionalId"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("PasajeAdicionalId", PasajeAdicionalId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("PasajeAdicionalId: {0}{1}",
								PasajeAdicionalId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PasajeAdicionalColumn Enum
	
	/// <summary>
	/// Enumerate the PasajeAdicional columns.
	/// </summary>
	[Serializable]
	public enum PasajeAdicionalColumn : int
	{
		/// <summary>
		/// PasajeAdicionalId : 
		/// </summary>
		[EnumTextValue("PasajeAdicionalID")]
		[ColumnEnum("PasajeAdicionalID", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		PasajeAdicionalId = 1,
		/// <summary>
		/// PasajeId : 
		/// </summary>
		[EnumTextValue("PasajeID")]
		[ColumnEnum("PasajeID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
		PasajeId = 2,
		/// <summary>
		/// AdicionalId : 
		/// </summary>
		[EnumTextValue("AdicionalID")]
		[ColumnEnum("AdicionalID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
		AdicionalId = 3
	}//End enum

	#endregion PasajeAdicionalColumn Enum

} // end namespace
