
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PasajeroMenor.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using MAT.Entities.Validation;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'PasajeroMenor' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PasajeroMenorBase : EntityBase, IPasajeroMenor, IEntityId<PasajeroMenorKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PasajeroMenorEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PasajeroMenorEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PasajeroMenorEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PasajeroMenor> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PasajeroMenorEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PasajeroMenorEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PasajeroMenorBase"/> instance.
		///</summary>
		public PasajeroMenorBase()
		{
			this.entityData = new PasajeroMenorEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PasajeroMenorBase"/> instance.
		///</summary>
		///<param name="_pasajeid"></param>
		///<param name="_pasajeroid"></param>
		///<param name="_menorid"></param>
		public PasajeroMenorBase(System.Guid _pasajeid, System.Guid _pasajeroid, System.Guid _menorid)
		{
			this.entityData = new PasajeroMenorEntityData();
			this.backupData = null;

			this.Pasajeid = _pasajeid;
			this.Pasajeroid = _pasajeroid;
			this.Menorid = _menorid;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PasajeroMenor"/> instance.
		///</summary>
		///<param name="_pasajeid"></param>
		///<param name="_pasajeroid"></param>
		///<param name="_menorid"></param>
		public static PasajeroMenor CreatePasajeroMenor(System.Guid _pasajeid, System.Guid _pasajeroid, System.Guid _menorid)
		{
			PasajeroMenor newPasajeroMenor = new PasajeroMenor();
			newPasajeroMenor.Pasajeid = _pasajeid;
			newPasajeroMenor.Pasajeroid = _pasajeroid;
			newPasajeroMenor.Menorid = _menorid;
			return newPasajeroMenor;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(PasajeroMenorColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeroMenorColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Pasajeid property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Pasajeid is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid Pasajeid
		{
			get
			{
				return this.entityData.Pasajeid; 
			}
			
			set
			{
				if (this.entityData.Pasajeid == value)
					return;
				
                OnPropertyChanging("Pasajeid");                    
				OnColumnChanging(PasajeroMenorColumn.Pasajeid, this.entityData.Pasajeid);
				this.entityData.Pasajeid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeroMenorColumn.Pasajeid, this.entityData.Pasajeid);
				OnPropertyChanged("Pasajeid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Pasajeroid property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Pasajeroid is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid Pasajeroid
		{
			get
			{
				return this.entityData.Pasajeroid; 
			}
			
			set
			{
				if (this.entityData.Pasajeroid == value)
					return;
				
                OnPropertyChanging("Pasajeroid");                    
				OnColumnChanging(PasajeroMenorColumn.Pasajeroid, this.entityData.Pasajeroid);
				this.entityData.Pasajeroid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeroMenorColumn.Pasajeroid, this.entityData.Pasajeroid);
				OnPropertyChanged("Pasajeroid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Menorid property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Menorid is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid Menorid
		{
			get
			{
				return this.entityData.Menorid; 
			}
			
			set
			{
				if (this.entityData.Menorid == value)
					return;
				
                OnPropertyChanging("Menorid");                    
				OnColumnChanging(PasajeroMenorColumn.Menorid, this.entityData.Menorid);
				this.entityData.Menorid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PasajeroMenorColumn.Menorid, this.entityData.Menorid);
				OnPropertyChanged("Menorid");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Cliente"/>.
		/// </summary>
		/// <value>The source Cliente for Menorid.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Cliente MenoridSource
      	{
            get { return entityData.MenoridSource; }
            set { entityData.MenoridSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Cliente"/>.
		/// </summary>
		/// <value>The source Cliente for Pasajeroid.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Cliente PasajeroidSource
      	{
            get { return entityData.PasajeroidSource; }
            set { entityData.PasajeroidSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PasajeroMenor"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"id", "pasajeid", "pasajeroid", "menorid"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PasajeroMenorEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PasajeroMenor) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PasajeroMenor>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PasajeroMenor);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PasajeroMenor Entity 
		///</summary>
		protected virtual PasajeroMenor Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			PasajeroMenor copy = new PasajeroMenor();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.Pasajeid = this.Pasajeid;
				copy.Pasajeroid = this.Pasajeroid;
				copy.Menorid = this.Menorid;
			
			if (this.MenoridSource != null && existingCopies.Contains(this.MenoridSource))
				copy.MenoridSource = existingCopies[this.MenoridSource] as Cliente;
			else
				copy.MenoridSource = MakeCopyOf(this.MenoridSource, existingCopies) as Cliente;
			if (this.PasajeroidSource != null && existingCopies.Contains(this.PasajeroidSource))
				copy.PasajeroidSource = existingCopies[this.PasajeroidSource] as Cliente;
			else
				copy.PasajeroidSource = MakeCopyOf(this.PasajeroidSource, existingCopies) as Cliente;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed PasajeroMenor Entity 
		///</summary>
		public virtual PasajeroMenor Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed PasajeroMenor Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PasajeroMenor DeepCopy()
		{
			return EntityHelper.Clone<PasajeroMenor>(this as PasajeroMenor);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PasajeroMenorEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PasajeroMenorEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PasajeroMenorEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PasajeroMenorColumn column)
		{
			switch(column)
			{
					case PasajeroMenorColumn.Id:
					return entityData.Id != _originalData.Id;
					case PasajeroMenorColumn.Pasajeid:
					return entityData.Pasajeid != _originalData.Pasajeid;
					case PasajeroMenorColumn.Pasajeroid:
					return entityData.Pasajeroid != _originalData.Pasajeroid;
					case PasajeroMenorColumn.Menorid:
					return entityData.Menorid != _originalData.Menorid;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PasajeroMenorColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.Pasajeid != _originalData.Pasajeid;
			result = result || entityData.Pasajeroid != _originalData.Pasajeroid;
			result = result || entityData.Menorid != _originalData.Menorid;
			return result;
		}	
		
		///<summary>
		///  Returns a PasajeroMenor Entity with the original data.
		///</summary>
		public PasajeroMenor GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePasajeroMenor(
				_originalData.Pasajeid,
				_originalData.Pasajeroid,
				_originalData.Menorid
				);
				
			return (PasajeroMenor)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PasajeroMenorBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PasajeroMenorBase)
				return ValueEquals(this, (PasajeroMenorBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PasajeroMenorBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.Pasajeid.GetHashCode() ^ 
					this.Pasajeroid.GetHashCode() ^ 
					this.Menorid.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PasajeroMenorBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PasajeroMenorBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PasajeroMenorBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PasajeroMenorBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PasajeroMenorBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PasajeroMenorBase Object1, PasajeroMenorBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.Pasajeid != Object2.Pasajeid)
				equal = false;
			if (Object1.Pasajeroid != Object2.Pasajeroid)
				equal = false;
			if (Object1.Menorid != Object2.Menorid)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PasajeroMenorBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PasajeroMenorComparer GetComparer()
        {
            return new PasajeroMenorComparer();
        }
        */

        // Comparer delegates back to PasajeroMenor
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PasajeroMenor rhs, PasajeroMenorColumn which)
        {
            switch (which)
            {
            	
            	
            	case PasajeroMenorColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case PasajeroMenorColumn.Pasajeid:
            		return this.Pasajeid.CompareTo(rhs.Pasajeid);
            		
            		                 
            	
            	
            	case PasajeroMenorColumn.Pasajeroid:
            		return this.Pasajeroid.CompareTo(rhs.Pasajeroid);
            		
            		                 
            	
            	
            	case PasajeroMenorColumn.Menorid:
            		return this.Menorid.CompareTo(rhs.Menorid);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PasajeroMenorKey> Members
		
		// member variable for the EntityId property
		private PasajeroMenorKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PasajeroMenorKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PasajeroMenorKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PasajeroMenor")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- Id: {0}{4}- Pasajeid: {1}{4}- Pasajeroid: {2}{4}- Menorid: {3}{4}{6}", 
				this.Id,
				this.Pasajeid,
				this.Pasajeroid,
				this.Menorid,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PasajeroMenor' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PasajeroMenorEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PasajeroMenor"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// pasajeid : 
		/// </summary>
		public System.Guid Pasajeid = Guid.Empty;
		
		/// <summary>
		/// pasajeroid : 
		/// </summary>
		public System.Guid Pasajeroid = Guid.Empty;
		
		/// <summary>
		/// menorid : 
		/// </summary>
		public System.Guid Menorid = Guid.Empty;
		#endregion
			
		#region Source Foreign Key Property
				
		private Cliente _menoridSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Cliente"/>.
		/// </summary>
		/// <value>The source Cliente for Menorid.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Cliente MenoridSource
      	{
            get { return this._menoridSource; }
            set { this._menoridSource = value; }
      	}
		private Cliente _pasajeroidSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Cliente"/>.
		/// </summary>
		/// <value>The source Cliente for Pasajeroid.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Cliente PasajeroidSource
      	{
            get { return this._pasajeroidSource; }
            set { this._pasajeroidSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PasajeroMenorEntityData _tmp = new PasajeroMenorEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Pasajeid = this.Pasajeid;
			_tmp.Pasajeroid = this.Pasajeroid;
			_tmp.Menorid = this.Menorid;
			
			#region Source Parent Composite Entities
			if (this.MenoridSource != null)
				_tmp.MenoridSource = MakeCopyOf(this.MenoridSource) as Cliente;
			if (this.PasajeroidSource != null)
				_tmp.PasajeroidSource = MakeCopyOf(this.PasajeroidSource) as Cliente;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PasajeroMenorEntityData _tmp = new PasajeroMenorEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.Pasajeid = this.Pasajeid;
			_tmp.Pasajeroid = this.Pasajeroid;
			_tmp.Menorid = this.Menorid;
			
			#region Source Parent Composite Entities
			if (this.MenoridSource != null && existingCopies.Contains(this.MenoridSource))
				_tmp.MenoridSource = existingCopies[this.MenoridSource] as Cliente;
			else
				_tmp.MenoridSource = MakeCopyOf(this.MenoridSource, existingCopies) as Cliente;
			if (this.PasajeroidSource != null && existingCopies.Contains(this.PasajeroidSource))
				_tmp.PasajeroidSource = existingCopies[this.PasajeroidSource] as Cliente;
			else
				_tmp.PasajeroidSource = MakeCopyOf(this.PasajeroidSource, existingCopies) as Cliente;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeroMenorColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PasajeroMenorColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeroMenorColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PasajeroMenorColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeroMenorColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PasajeroMenorColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PasajeroMenorEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PasajeroMenorEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PasajeroMenorColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PasajeroMenorColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PasajeroMenorEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PasajeroMenorEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PasajeroMenorEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PasajeroMenor"/> object.
	/// </remarks>
	public class PasajeroMenorEventArgs : System.EventArgs
	{
		private PasajeroMenorColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PasajeroMenorEventArgs class.
		///</summary>
		public PasajeroMenorEventArgs(PasajeroMenorColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PasajeroMenorEventArgs class.
		///</summary>
		public PasajeroMenorEventArgs(PasajeroMenorColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PasajeroMenorColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PasajeroMenorColumn" />
		public PasajeroMenorColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PasajeroMenor related events.
	///</summary>
	public delegate void PasajeroMenorEventHandler(object sender, PasajeroMenorEventArgs e);
	
	#region PasajeroMenorComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PasajeroMenorComparer : System.Collections.Generic.IComparer<PasajeroMenor>
	{
		PasajeroMenorColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PasajeroMenorComparer"/> class.
        /// </summary>
		public PasajeroMenorComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PasajeroMenorComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PasajeroMenorComparer(PasajeroMenorColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="PasajeroMenor"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="PasajeroMenor"/> to compare.</param>
        /// <param name="b">The second <c>PasajeroMenor</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PasajeroMenor a, PasajeroMenor b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PasajeroMenor entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PasajeroMenor a, PasajeroMenor b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PasajeroMenorColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PasajeroMenorKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PasajeroMenor"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PasajeroMenorKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PasajeroMenorKey class.
		/// </summary>
		public PasajeroMenorKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PasajeroMenorKey class.
		/// </summary>
		public PasajeroMenorKey(PasajeroMenorBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PasajeroMenorKey class.
		/// </summary>
		public PasajeroMenorKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PasajeroMenorBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PasajeroMenorBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PasajeroMenorColumn Enum
	
	/// <summary>
	/// Enumerate the PasajeroMenor columns.
	/// </summary>
	[Serializable]
	public enum PasajeroMenorColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("id")]
		[ColumnEnum("id", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// Pasajeid : 
		/// </summary>
		[EnumTextValue("pasajeid")]
		[ColumnEnum("pasajeid", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		Pasajeid = 2,
		/// <summary>
		/// Pasajeroid : 
		/// </summary>
		[EnumTextValue("pasajeroid")]
		[ColumnEnum("pasajeroid", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		Pasajeroid = 3,
		/// <summary>
		/// Menorid : 
		/// </summary>
		[EnumTextValue("menorid")]
		[ColumnEnum("menorid", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		Menorid = 4
	}//End enum

	#endregion PasajeroMenorColumn Enum

} // end namespace
