
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PlanillaServicio.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using MAT.Entities.Validation;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'PlanillaServicio' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PlanillaServicioBase : EntityBase, IPlanillaServicio, IEntityId<PlanillaServicioKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PlanillaServicioEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PlanillaServicioEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PlanillaServicioEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PlanillaServicio> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PlanillaServicioEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PlanillaServicioEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PlanillaServicioBase"/> instance.
		///</summary>
		public PlanillaServicioBase()
		{
			this.entityData = new PlanillaServicioEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PlanillaServicioBase"/> instance.
		///</summary>
		///<param name="_planillaServicioId"></param>
		///<param name="_viajeId"></param>
		///<param name="_fechaRegistro"></param>
		///<param name="_total"></param>
		public PlanillaServicioBase(System.Guid _planillaServicioId, System.Guid _viajeId, 
			System.DateTime _fechaRegistro, System.Double _total)
		{
			this.entityData = new PlanillaServicioEntityData();
			this.backupData = null;

			this.PlanillaServicioId = _planillaServicioId;
			this.ViajeId = _viajeId;
			this.FechaRegistro = _fechaRegistro;
			this.Total = _total;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PlanillaServicio"/> instance.
		///</summary>
		///<param name="_planillaServicioId"></param>
		///<param name="_viajeId"></param>
		///<param name="_fechaRegistro"></param>
		///<param name="_total"></param>
		public static PlanillaServicio CreatePlanillaServicio(System.Guid _planillaServicioId, System.Guid _viajeId, 
			System.DateTime _fechaRegistro, System.Double _total)
		{
			PlanillaServicio newPlanillaServicio = new PlanillaServicio();
			newPlanillaServicio.PlanillaServicioId = _planillaServicioId;
			newPlanillaServicio.ViajeId = _viajeId;
			newPlanillaServicio.FechaRegistro = _fechaRegistro;
			newPlanillaServicio.Total = _total;
			return newPlanillaServicio;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the PlanillaServicioId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "PlanillaServicioId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid PlanillaServicioId
		{
			get
			{
				return this.entityData.PlanillaServicioId; 
			}
			
			set
			{
				if (this.entityData.PlanillaServicioId == value)
					return;
				
                OnPropertyChanging("PlanillaServicioId");                    
				OnColumnChanging(PlanillaServicioColumn.PlanillaServicioId, this.entityData.PlanillaServicioId);
				this.entityData.PlanillaServicioId = value;
				this.EntityId.PlanillaServicioId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PlanillaServicioColumn.PlanillaServicioId, this.entityData.PlanillaServicioId);
				OnPropertyChanged("PlanillaServicioId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the PlanillaServicioID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the PlanillaServicioID property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalPlanillaServicioId
		{
			get { return this.entityData.OriginalPlanillaServicioId; }
			set { this.entityData.OriginalPlanillaServicioId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the ViajeId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "ViajeId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid ViajeId
		{
			get
			{
				return this.entityData.ViajeId; 
			}
			
			set
			{
				if (this.entityData.ViajeId == value)
					return;
				
                OnPropertyChanging("ViajeId");                    
				OnColumnChanging(PlanillaServicioColumn.ViajeId, this.entityData.ViajeId);
				this.entityData.ViajeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PlanillaServicioColumn.ViajeId, this.entityData.ViajeId);
				OnPropertyChanged("ViajeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FechaRegistro property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "FechaRegistro is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime FechaRegistro
		{
			get
			{
				return this.entityData.FechaRegistro; 
			}
			
			set
			{
				if (this.entityData.FechaRegistro == value)
					return;
				
                OnPropertyChanging("FechaRegistro");                    
				OnColumnChanging(PlanillaServicioColumn.FechaRegistro, this.entityData.FechaRegistro);
				this.entityData.FechaRegistro = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PlanillaServicioColumn.FechaRegistro, this.entityData.FechaRegistro);
				OnPropertyChanged("FechaRegistro");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Total property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Total is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Total
		{
			get
			{
				return this.entityData.Total; 
			}
			
			set
			{
				if (this.entityData.Total == value)
					return;
				
                OnPropertyChanging("Total");                    
				OnColumnChanging(PlanillaServicioColumn.Total, this.entityData.Total);
				this.entityData.Total = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PlanillaServicioColumn.Total, this.entityData.Total);
				OnPropertyChanged("Total");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of PlanillaServicioItem objects
		///	which are related to this object through the relation FK_PlanillaServicioItem_PlanillaServicio
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<PlanillaServicioItem> PlanillaServicioItemCollection
		{
			get { return entityData.PlanillaServicioItemCollection; }
			set { entityData.PlanillaServicioItemCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PlanillaServicio"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"PlanillaServicioID", "ViajeID", "FechaRegistro", "Total"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PlanillaServicioEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PlanillaServicio) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PlanillaServicio>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PlanillaServicio);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PlanillaServicio Entity 
		///</summary>
		protected virtual PlanillaServicio Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			PlanillaServicio copy = new PlanillaServicio();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.PlanillaServicioId = this.PlanillaServicioId;
					copy.OriginalPlanillaServicioId = this.OriginalPlanillaServicioId;
				copy.ViajeId = this.ViajeId;
				copy.FechaRegistro = this.FechaRegistro;
				copy.Total = this.Total;
			
		
			//deep copy nested objects
			copy.PlanillaServicioItemCollection = (TList<PlanillaServicioItem>) MakeCopyOf(this.PlanillaServicioItemCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed PlanillaServicio Entity 
		///</summary>
		public virtual PlanillaServicio Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed PlanillaServicio Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PlanillaServicio DeepCopy()
		{
			return EntityHelper.Clone<PlanillaServicio>(this as PlanillaServicio);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PlanillaServicioEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PlanillaServicioEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PlanillaServicioEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PlanillaServicioColumn column)
		{
			switch(column)
			{
					case PlanillaServicioColumn.PlanillaServicioId:
					return entityData.PlanillaServicioId != _originalData.PlanillaServicioId;
					case PlanillaServicioColumn.ViajeId:
					return entityData.ViajeId != _originalData.ViajeId;
					case PlanillaServicioColumn.FechaRegistro:
					return entityData.FechaRegistro != _originalData.FechaRegistro;
					case PlanillaServicioColumn.Total:
					return entityData.Total != _originalData.Total;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PlanillaServicioColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.PlanillaServicioId != _originalData.PlanillaServicioId;
			result = result || entityData.ViajeId != _originalData.ViajeId;
			result = result || entityData.FechaRegistro != _originalData.FechaRegistro;
			result = result || entityData.Total != _originalData.Total;
			return result;
		}	
		
		///<summary>
		///  Returns a PlanillaServicio Entity with the original data.
		///</summary>
		public PlanillaServicio GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePlanillaServicio(
				_originalData.PlanillaServicioId,
				_originalData.ViajeId,
				_originalData.FechaRegistro,
				_originalData.Total
				);
				
			return (PlanillaServicio)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PlanillaServicioBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PlanillaServicioBase)
				return ValueEquals(this, (PlanillaServicioBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PlanillaServicioBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.PlanillaServicioId.GetHashCode() ^ 
					this.ViajeId.GetHashCode() ^ 
					this.FechaRegistro.GetHashCode() ^ 
					this.Total.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PlanillaServicioBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PlanillaServicioBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PlanillaServicioBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PlanillaServicioBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PlanillaServicioBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PlanillaServicioBase Object1, PlanillaServicioBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.PlanillaServicioId != Object2.PlanillaServicioId)
				equal = false;
			if (Object1.ViajeId != Object2.ViajeId)
				equal = false;
			if (Object1.FechaRegistro != Object2.FechaRegistro)
				equal = false;
			if (Object1.Total != Object2.Total)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PlanillaServicioBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PlanillaServicioComparer GetComparer()
        {
            return new PlanillaServicioComparer();
        }
        */

        // Comparer delegates back to PlanillaServicio
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PlanillaServicio rhs, PlanillaServicioColumn which)
        {
            switch (which)
            {
            	
            	
            	case PlanillaServicioColumn.PlanillaServicioId:
            		return this.PlanillaServicioId.CompareTo(rhs.PlanillaServicioId);
            		
            		                 
            	
            	
            	case PlanillaServicioColumn.ViajeId:
            		return this.ViajeId.CompareTo(rhs.ViajeId);
            		
            		                 
            	
            	
            	case PlanillaServicioColumn.FechaRegistro:
            		return this.FechaRegistro.CompareTo(rhs.FechaRegistro);
            		
            		                 
            	
            	
            	case PlanillaServicioColumn.Total:
            		return this.Total.CompareTo(rhs.Total);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PlanillaServicioKey> Members
		
		// member variable for the EntityId property
		private PlanillaServicioKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PlanillaServicioKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PlanillaServicioKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PlanillaServicio")
					.Append("|").Append( this.PlanillaServicioId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- PlanillaServicioId: {0}{4}- ViajeId: {1}{4}- FechaRegistro: {2}{4}- Total: {3}{4}{6}", 
				this.PlanillaServicioId,
				this.ViajeId,
				this.FechaRegistro,
				this.Total,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PlanillaServicio' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PlanillaServicioEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// PlanillaServicioID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PlanillaServicio"</remarks>
		public System.Guid PlanillaServicioId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalPlanillaServicioId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// ViajeID : 
		/// </summary>
		public System.Guid ViajeId = Guid.Empty;
		
		/// <summary>
		/// FechaRegistro : 
		/// </summary>
		public System.DateTime FechaRegistro = DateTime.MinValue;
		
		/// <summary>
		/// Total : 
		/// </summary>
		public System.Double Total = 0.0f;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region PlanillaServicioItemCollection
		
		private TList<PlanillaServicioItem> _planillaServicioItemPlanillaServicioId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _planillaServicioItemPlanillaServicioId
		/// </summary>
		
		public TList<PlanillaServicioItem> PlanillaServicioItemCollection
		{
			get
			{
				if (_planillaServicioItemPlanillaServicioId == null)
				{
				_planillaServicioItemPlanillaServicioId = new TList<PlanillaServicioItem>();
				}
	
				return _planillaServicioItemPlanillaServicioId;
			}
			set { _planillaServicioItemPlanillaServicioId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PlanillaServicioEntityData _tmp = new PlanillaServicioEntityData();
						
			_tmp.PlanillaServicioId = this.PlanillaServicioId;
			_tmp.OriginalPlanillaServicioId = this.OriginalPlanillaServicioId;
			
			_tmp.ViajeId = this.ViajeId;
			_tmp.FechaRegistro = this.FechaRegistro;
			_tmp.Total = this.Total;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._planillaServicioItemPlanillaServicioId != null)
				_tmp.PlanillaServicioItemCollection = (TList<PlanillaServicioItem>) MakeCopyOf(this.PlanillaServicioItemCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PlanillaServicioEntityData _tmp = new PlanillaServicioEntityData();
						
			_tmp.PlanillaServicioId = this.PlanillaServicioId;
			_tmp.OriginalPlanillaServicioId = this.OriginalPlanillaServicioId;
			
			_tmp.ViajeId = this.ViajeId;
			_tmp.FechaRegistro = this.FechaRegistro;
			_tmp.Total = this.Total;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.PlanillaServicioItemCollection = (TList<PlanillaServicioItem>) MakeCopyOf(this.PlanillaServicioItemCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PlanillaServicioColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PlanillaServicioColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PlanillaServicioColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PlanillaServicioColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PlanillaServicioColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PlanillaServicioColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PlanillaServicioEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PlanillaServicioEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PlanillaServicioColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PlanillaServicioColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PlanillaServicioEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PlanillaServicioEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PlanillaServicioEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PlanillaServicio"/> object.
	/// </remarks>
	public class PlanillaServicioEventArgs : System.EventArgs
	{
		private PlanillaServicioColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PlanillaServicioEventArgs class.
		///</summary>
		public PlanillaServicioEventArgs(PlanillaServicioColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PlanillaServicioEventArgs class.
		///</summary>
		public PlanillaServicioEventArgs(PlanillaServicioColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PlanillaServicioColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PlanillaServicioColumn" />
		public PlanillaServicioColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PlanillaServicio related events.
	///</summary>
	public delegate void PlanillaServicioEventHandler(object sender, PlanillaServicioEventArgs e);
	
	#region PlanillaServicioComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PlanillaServicioComparer : System.Collections.Generic.IComparer<PlanillaServicio>
	{
		PlanillaServicioColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PlanillaServicioComparer"/> class.
        /// </summary>
		public PlanillaServicioComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PlanillaServicioComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PlanillaServicioComparer(PlanillaServicioColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="PlanillaServicio"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="PlanillaServicio"/> to compare.</param>
        /// <param name="b">The second <c>PlanillaServicio</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PlanillaServicio a, PlanillaServicio b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PlanillaServicio entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PlanillaServicio a, PlanillaServicio b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PlanillaServicioColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PlanillaServicioKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PlanillaServicio"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PlanillaServicioKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PlanillaServicioKey class.
		/// </summary>
		public PlanillaServicioKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PlanillaServicioKey class.
		/// </summary>
		public PlanillaServicioKey(PlanillaServicioBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.PlanillaServicioId = entity.PlanillaServicioId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PlanillaServicioKey class.
		/// </summary>
		public PlanillaServicioKey(System.Guid _planillaServicioId)
		{
			#region Init Properties

			this.PlanillaServicioId = _planillaServicioId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PlanillaServicioBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PlanillaServicioBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the PlanillaServicioId property
		private System.Guid _planillaServicioId;
		
		/// <summary>
		/// Gets or sets the PlanillaServicioId property.
		/// </summary>
		public System.Guid PlanillaServicioId
		{
			get { return _planillaServicioId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.PlanillaServicioId = value;
				
				_planillaServicioId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				PlanillaServicioId = ( values["PlanillaServicioId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["PlanillaServicioId"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("PlanillaServicioId", PlanillaServicioId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("PlanillaServicioId: {0}{1}",
								PlanillaServicioId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PlanillaServicioColumn Enum
	
	/// <summary>
	/// Enumerate the PlanillaServicio columns.
	/// </summary>
	[Serializable]
	public enum PlanillaServicioColumn : int
	{
		/// <summary>
		/// PlanillaServicioId : 
		/// </summary>
		[EnumTextValue("PlanillaServicioID")]
		[ColumnEnum("PlanillaServicioID", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		PlanillaServicioId = 1,
		/// <summary>
		/// ViajeId : 
		/// </summary>
		[EnumTextValue("ViajeID")]
		[ColumnEnum("ViajeID", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		ViajeId = 2,
		/// <summary>
		/// FechaRegistro : 
		/// </summary>
		[EnumTextValue("FechaRegistro")]
		[ColumnEnum("FechaRegistro", typeof(System.DateTime), System.Data.DbType.Date, false, false, false)]
		FechaRegistro = 3,
		/// <summary>
		/// Total : 
		/// </summary>
		[EnumTextValue("Total")]
		[ColumnEnum("Total", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Total = 4
	}//End enum

	#endregion PlanillaServicioColumn Enum

} // end namespace
