
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Viaje.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using MAT.Entities.Validation;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'Viaje' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ViajeBase : EntityBase, IViaje, IEntityId<ViajeKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ViajeEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ViajeEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ViajeEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Viaje> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ViajeEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ViajeEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ViajeBase"/> instance.
		///</summary>
		public ViajeBase()
		{
			this.entityData = new ViajeEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ViajeBase"/> instance.
		///</summary>
		///<param name="_viajeId"></param>
		///<param name="_paqueteId"></param>
		///<param name="_origen"></param>
		///<param name="_fechaSalida"></param>
		///<param name="_horaSalida"></param>
		///<param name="_paisOrigen"></param>
		///<param name="_paisDestino"></param>
		///<param name="_paso"></param>
		///<param name="_medio"></param>
		///<param name="_busId"></param>
		///<param name="_fechaRegreso"></param>
		///<param name="_horaRegreso"></param>
		///<param name="_descripcion"></param>
		///<param name="_precioSemicama"></param>
		///<param name="_precioCama"></param>
		///<param name="_precioPromocional"></param>
		///<param name="_fechaPromocion"></param>
		///<param name="_nDias"></param>
		///<param name="_nNoches"></param>
		public ViajeBase(System.Guid _viajeId, System.Guid? _paqueteId, System.String _origen, 
			System.DateTime? _fechaSalida, System.String _horaSalida, System.String _paisOrigen, System.String _paisDestino, 
			System.String _paso, System.String _medio, System.Guid? _busId, System.DateTime? _fechaRegreso, System.String _horaRegreso, 
			System.String _descripcion, System.Double? _precioSemicama, System.Double? _precioCama, System.Double? _precioPromocional, 
			System.DateTime? _fechaPromocion, System.Int32? _nDias, System.Int32? _nNoches)
		{
			this.entityData = new ViajeEntityData();
			this.backupData = null;

			this.ViajeId = _viajeId;
			this.PaqueteId = _paqueteId;
			this.Origen = _origen;
			this.FechaSalida = _fechaSalida;
			this.HoraSalida = _horaSalida;
			this.PaisOrigen = _paisOrigen;
			this.PaisDestino = _paisDestino;
			this.Paso = _paso;
			this.Medio = _medio;
			this.BusId = _busId;
			this.FechaRegreso = _fechaRegreso;
			this.HoraRegreso = _horaRegreso;
			this.Descripcion = _descripcion;
			this.PrecioSemicama = _precioSemicama;
			this.PrecioCama = _precioCama;
			this.PrecioPromocional = _precioPromocional;
			this.FechaPromocion = _fechaPromocion;
			this.NDias = _nDias;
			this.NNoches = _nNoches;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Viaje"/> instance.
		///</summary>
		///<param name="_viajeId"></param>
		///<param name="_paqueteId"></param>
		///<param name="_origen"></param>
		///<param name="_fechaSalida"></param>
		///<param name="_horaSalida"></param>
		///<param name="_paisOrigen"></param>
		///<param name="_paisDestino"></param>
		///<param name="_paso"></param>
		///<param name="_medio"></param>
		///<param name="_busId"></param>
		///<param name="_fechaRegreso"></param>
		///<param name="_horaRegreso"></param>
		///<param name="_descripcion"></param>
		///<param name="_precioSemicama"></param>
		///<param name="_precioCama"></param>
		///<param name="_precioPromocional"></param>
		///<param name="_fechaPromocion"></param>
		///<param name="_nDias"></param>
		///<param name="_nNoches"></param>
		public static Viaje CreateViaje(System.Guid _viajeId, System.Guid? _paqueteId, System.String _origen, 
			System.DateTime? _fechaSalida, System.String _horaSalida, System.String _paisOrigen, System.String _paisDestino, 
			System.String _paso, System.String _medio, System.Guid? _busId, System.DateTime? _fechaRegreso, System.String _horaRegreso, 
			System.String _descripcion, System.Double? _precioSemicama, System.Double? _precioCama, System.Double? _precioPromocional, 
			System.DateTime? _fechaPromocion, System.Int32? _nDias, System.Int32? _nNoches)
		{
			Viaje newViaje = new Viaje();
			newViaje.ViajeId = _viajeId;
			newViaje.PaqueteId = _paqueteId;
			newViaje.Origen = _origen;
			newViaje.FechaSalida = _fechaSalida;
			newViaje.HoraSalida = _horaSalida;
			newViaje.PaisOrigen = _paisOrigen;
			newViaje.PaisDestino = _paisDestino;
			newViaje.Paso = _paso;
			newViaje.Medio = _medio;
			newViaje.BusId = _busId;
			newViaje.FechaRegreso = _fechaRegreso;
			newViaje.HoraRegreso = _horaRegreso;
			newViaje.Descripcion = _descripcion;
			newViaje.PrecioSemicama = _precioSemicama;
			newViaje.PrecioCama = _precioCama;
			newViaje.PrecioPromocional = _precioPromocional;
			newViaje.FechaPromocion = _fechaPromocion;
			newViaje.NDias = _nDias;
			newViaje.NNoches = _nNoches;
			return newViaje;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ViajeId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "ViajeId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid ViajeId
		{
			get
			{
				return this.entityData.ViajeId; 
			}
			
			set
			{
				if (this.entityData.ViajeId == value)
					return;
				
                OnPropertyChanging("ViajeId");                    
				OnColumnChanging(ViajeColumn.ViajeId, this.entityData.ViajeId);
				this.entityData.ViajeId = value;
				this.EntityId.ViajeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.ViajeId, this.entityData.ViajeId);
				OnPropertyChanged("ViajeId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ViajeID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ViajeID property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalViajeId
		{
			get { return this.entityData.OriginalViajeId; }
			set { this.entityData.OriginalViajeId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the PaqueteId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return Guid.Empty. It is up to the developer
		/// to check the value of IsPaqueteIdNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Guid? PaqueteId
		{
			get
			{
				return this.entityData.PaqueteId; 
			}
			
			set
			{
				if (this.entityData.PaqueteId == value)
					return;
				
                OnPropertyChanging("PaqueteId");                    
				OnColumnChanging(ViajeColumn.PaqueteId, this.entityData.PaqueteId);
				this.entityData.PaqueteId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PaqueteId, this.entityData.PaqueteId);
				OnPropertyChanged("PaqueteId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Origen property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Origen
		{
			get
			{
				return this.entityData.Origen; 
			}
			
			set
			{
				if (this.entityData.Origen == value)
					return;
				
                OnPropertyChanging("Origen");                    
				OnColumnChanging(ViajeColumn.Origen, this.entityData.Origen);
				this.entityData.Origen = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.Origen, this.entityData.Origen);
				OnPropertyChanged("Origen");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FechaSalida property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsFechaSalidaNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? FechaSalida
		{
			get
			{
				return this.entityData.FechaSalida; 
			}
			
			set
			{
				if (this.entityData.FechaSalida == value)
					return;
				
                OnPropertyChanging("FechaSalida");                    
				OnColumnChanging(ViajeColumn.FechaSalida, this.entityData.FechaSalida);
				this.entityData.FechaSalida = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.FechaSalida, this.entityData.FechaSalida);
				OnPropertyChanged("FechaSalida");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HoraSalida property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String HoraSalida
		{
			get
			{
				return this.entityData.HoraSalida; 
			}
			
			set
			{
				if (this.entityData.HoraSalida == value)
					return;
				
                OnPropertyChanging("HoraSalida");                    
				OnColumnChanging(ViajeColumn.HoraSalida, this.entityData.HoraSalida);
				this.entityData.HoraSalida = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.HoraSalida, this.entityData.HoraSalida);
				OnPropertyChanged("HoraSalida");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PaisOrigen property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String PaisOrigen
		{
			get
			{
				return this.entityData.PaisOrigen; 
			}
			
			set
			{
				if (this.entityData.PaisOrigen == value)
					return;
				
                OnPropertyChanging("PaisOrigen");                    
				OnColumnChanging(ViajeColumn.PaisOrigen, this.entityData.PaisOrigen);
				this.entityData.PaisOrigen = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PaisOrigen, this.entityData.PaisOrigen);
				OnPropertyChanged("PaisOrigen");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PaisDestino property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String PaisDestino
		{
			get
			{
				return this.entityData.PaisDestino; 
			}
			
			set
			{
				if (this.entityData.PaisDestino == value)
					return;
				
                OnPropertyChanging("PaisDestino");                    
				OnColumnChanging(ViajeColumn.PaisDestino, this.entityData.PaisDestino);
				this.entityData.PaisDestino = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PaisDestino, this.entityData.PaisDestino);
				OnPropertyChanged("PaisDestino");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Paso property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Paso
		{
			get
			{
				return this.entityData.Paso; 
			}
			
			set
			{
				if (this.entityData.Paso == value)
					return;
				
                OnPropertyChanging("Paso");                    
				OnColumnChanging(ViajeColumn.Paso, this.entityData.Paso);
				this.entityData.Paso = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.Paso, this.entityData.Paso);
				OnPropertyChanged("Paso");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Medio property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Medio
		{
			get
			{
				return this.entityData.Medio; 
			}
			
			set
			{
				if (this.entityData.Medio == value)
					return;
				
                OnPropertyChanging("Medio");                    
				OnColumnChanging(ViajeColumn.Medio, this.entityData.Medio);
				this.entityData.Medio = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.Medio, this.entityData.Medio);
				OnPropertyChanged("Medio");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BusId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return Guid.Empty. It is up to the developer
		/// to check the value of IsBusIdNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Guid? BusId
		{
			get
			{
				return this.entityData.BusId; 
			}
			
			set
			{
				if (this.entityData.BusId == value)
					return;
				
                OnPropertyChanging("BusId");                    
				OnColumnChanging(ViajeColumn.BusId, this.entityData.BusId);
				this.entityData.BusId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.BusId, this.entityData.BusId);
				OnPropertyChanged("BusId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FechaRegreso property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsFechaRegresoNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? FechaRegreso
		{
			get
			{
				return this.entityData.FechaRegreso; 
			}
			
			set
			{
				if (this.entityData.FechaRegreso == value)
					return;
				
                OnPropertyChanging("FechaRegreso");                    
				OnColumnChanging(ViajeColumn.FechaRegreso, this.entityData.FechaRegreso);
				this.entityData.FechaRegreso = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.FechaRegreso, this.entityData.FechaRegreso);
				OnPropertyChanged("FechaRegreso");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HoraRegreso property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String HoraRegreso
		{
			get
			{
				return this.entityData.HoraRegreso; 
			}
			
			set
			{
				if (this.entityData.HoraRegreso == value)
					return;
				
                OnPropertyChanging("HoraRegreso");                    
				OnColumnChanging(ViajeColumn.HoraRegreso, this.entityData.HoraRegreso);
				this.entityData.HoraRegreso = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.HoraRegreso, this.entityData.HoraRegreso);
				OnPropertyChanged("HoraRegreso");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Descripcion property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String Descripcion
		{
			get
			{
				return this.entityData.Descripcion; 
			}
			
			set
			{
				if (this.entityData.Descripcion == value)
					return;
				
                OnPropertyChanging("Descripcion");                    
				OnColumnChanging(ViajeColumn.Descripcion, this.entityData.Descripcion);
				this.entityData.Descripcion = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.Descripcion, this.entityData.Descripcion);
				OnPropertyChanged("Descripcion");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PrecioSemicama property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0f. It is up to the developer
		/// to check the value of IsPrecioSemicamaNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Double? PrecioSemicama
		{
			get
			{
				return this.entityData.PrecioSemicama; 
			}
			
			set
			{
				if (this.entityData.PrecioSemicama == value)
					return;
				
                OnPropertyChanging("PrecioSemicama");                    
				OnColumnChanging(ViajeColumn.PrecioSemicama, this.entityData.PrecioSemicama);
				this.entityData.PrecioSemicama = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PrecioSemicama, this.entityData.PrecioSemicama);
				OnPropertyChanged("PrecioSemicama");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PrecioCama property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0f. It is up to the developer
		/// to check the value of IsPrecioCamaNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Double? PrecioCama
		{
			get
			{
				return this.entityData.PrecioCama; 
			}
			
			set
			{
				if (this.entityData.PrecioCama == value)
					return;
				
                OnPropertyChanging("PrecioCama");                    
				OnColumnChanging(ViajeColumn.PrecioCama, this.entityData.PrecioCama);
				this.entityData.PrecioCama = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PrecioCama, this.entityData.PrecioCama);
				OnPropertyChanged("PrecioCama");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PrecioPromocional property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0f. It is up to the developer
		/// to check the value of IsPrecioPromocionalNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Double? PrecioPromocional
		{
			get
			{
				return this.entityData.PrecioPromocional; 
			}
			
			set
			{
				if (this.entityData.PrecioPromocional == value)
					return;
				
                OnPropertyChanging("PrecioPromocional");                    
				OnColumnChanging(ViajeColumn.PrecioPromocional, this.entityData.PrecioPromocional);
				this.entityData.PrecioPromocional = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.PrecioPromocional, this.entityData.PrecioPromocional);
				OnPropertyChanged("PrecioPromocional");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FechaPromocion property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsFechaPromocionNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? FechaPromocion
		{
			get
			{
				return this.entityData.FechaPromocion; 
			}
			
			set
			{
				if (this.entityData.FechaPromocion == value)
					return;
				
                OnPropertyChanging("FechaPromocion");                    
				OnColumnChanging(ViajeColumn.FechaPromocion, this.entityData.FechaPromocion);
				this.entityData.FechaPromocion = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.FechaPromocion, this.entityData.FechaPromocion);
				OnPropertyChanged("FechaPromocion");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NDias property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsNDiasNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? NDias
		{
			get
			{
				return this.entityData.NDias; 
			}
			
			set
			{
				if (this.entityData.NDias == value)
					return;
				
                OnPropertyChanging("NDias");                    
				OnColumnChanging(ViajeColumn.NDias, this.entityData.NDias);
				this.entityData.NDias = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.NDias, this.entityData.NDias);
				OnPropertyChanged("NDias");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NNoches property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsNNochesNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? NNoches
		{
			get
			{
				return this.entityData.NNoches; 
			}
			
			set
			{
				if (this.entityData.NNoches == value)
					return;
				
                OnPropertyChanging("NNoches");                    
				OnColumnChanging(ViajeColumn.NNoches, this.entityData.NNoches);
				this.entityData.NNoches = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ViajeColumn.NNoches, this.entityData.NNoches);
				OnPropertyChanged("NNoches");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Paquete"/>.
		/// </summary>
		/// <value>The source Paquete for PaqueteId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Paquete PaqueteIdSource
      	{
            get { return entityData.PaqueteIdSource; }
            set { entityData.PaqueteIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Transporte"/>.
		/// </summary>
		/// <value>The source Transporte for BusId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Transporte BusIdSource
      	{
            get { return entityData.BusIdSource; }
            set { entityData.BusIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Pasaje objects
		///	which are related to this object through the relation FK_Pasaje_Viaje
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Pasaje> PasajeCollection
		{
			get { return entityData.PasajeCollection; }
			set { entityData.PasajeCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of ViajeHotel objects
		///	which are related to this object through the relation FK_ViajeHotel_Viaje
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<ViajeHotel> ViajeHotelCollection
		{
			get { return entityData.ViajeHotelCollection; }
			set { entityData.ViajeHotelCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Origen", "Origen", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HoraSalida", "Hora Salida", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PaisOrigen", "Pais Origen", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PaisDestino", "Pais Destino", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Paso", "Paso", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Medio", "Medio", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HoraRegreso", "Hora Regreso", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Descripcion", "Descripcion", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Viaje"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ViajeID", "PaqueteID", "Origen", "FechaSalida", "HoraSalida", "PaisOrigen", "PaisDestino", "Paso", "Medio", "BusID", "FechaRegreso", "HoraRegreso", "Descripcion", "PrecioSemicama", "PrecioCama", "PrecioPromocional", "FechaPromocion", "nDias", "nNoches"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ViajeEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Viaje) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Viaje>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Viaje);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Viaje Entity 
		///</summary>
		protected virtual Viaje Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Viaje copy = new Viaje();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ViajeId = this.ViajeId;
					copy.OriginalViajeId = this.OriginalViajeId;
				copy.PaqueteId = this.PaqueteId;
				copy.Origen = this.Origen;
				copy.FechaSalida = this.FechaSalida;
				copy.HoraSalida = this.HoraSalida;
				copy.PaisOrigen = this.PaisOrigen;
				copy.PaisDestino = this.PaisDestino;
				copy.Paso = this.Paso;
				copy.Medio = this.Medio;
				copy.BusId = this.BusId;
				copy.FechaRegreso = this.FechaRegreso;
				copy.HoraRegreso = this.HoraRegreso;
				copy.Descripcion = this.Descripcion;
				copy.PrecioSemicama = this.PrecioSemicama;
				copy.PrecioCama = this.PrecioCama;
				copy.PrecioPromocional = this.PrecioPromocional;
				copy.FechaPromocion = this.FechaPromocion;
				copy.NDias = this.NDias;
				copy.NNoches = this.NNoches;
			
			if (this.PaqueteIdSource != null && existingCopies.Contains(this.PaqueteIdSource))
				copy.PaqueteIdSource = existingCopies[this.PaqueteIdSource] as Paquete;
			else
				copy.PaqueteIdSource = MakeCopyOf(this.PaqueteIdSource, existingCopies) as Paquete;
			if (this.BusIdSource != null && existingCopies.Contains(this.BusIdSource))
				copy.BusIdSource = existingCopies[this.BusIdSource] as Transporte;
			else
				copy.BusIdSource = MakeCopyOf(this.BusIdSource, existingCopies) as Transporte;
		
			//deep copy nested objects
			copy.PasajeCollection = (TList<Pasaje>) MakeCopyOf(this.PasajeCollection, existingCopies); 
			copy.ViajeHotelCollection = (TList<ViajeHotel>) MakeCopyOf(this.ViajeHotelCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Viaje Entity 
		///</summary>
		public virtual Viaje Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Viaje Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Viaje DeepCopy()
		{
			return EntityHelper.Clone<Viaje>(this as Viaje);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ViajeEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ViajeEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ViajeEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ViajeColumn column)
		{
			switch(column)
			{
					case ViajeColumn.ViajeId:
					return entityData.ViajeId != _originalData.ViajeId;
					case ViajeColumn.PaqueteId:
					return entityData.PaqueteId != _originalData.PaqueteId;
					case ViajeColumn.Origen:
					return entityData.Origen != _originalData.Origen;
					case ViajeColumn.FechaSalida:
					return entityData.FechaSalida != _originalData.FechaSalida;
					case ViajeColumn.HoraSalida:
					return entityData.HoraSalida != _originalData.HoraSalida;
					case ViajeColumn.PaisOrigen:
					return entityData.PaisOrigen != _originalData.PaisOrigen;
					case ViajeColumn.PaisDestino:
					return entityData.PaisDestino != _originalData.PaisDestino;
					case ViajeColumn.Paso:
					return entityData.Paso != _originalData.Paso;
					case ViajeColumn.Medio:
					return entityData.Medio != _originalData.Medio;
					case ViajeColumn.BusId:
					return entityData.BusId != _originalData.BusId;
					case ViajeColumn.FechaRegreso:
					return entityData.FechaRegreso != _originalData.FechaRegreso;
					case ViajeColumn.HoraRegreso:
					return entityData.HoraRegreso != _originalData.HoraRegreso;
					case ViajeColumn.Descripcion:
					return entityData.Descripcion != _originalData.Descripcion;
					case ViajeColumn.PrecioSemicama:
					return entityData.PrecioSemicama != _originalData.PrecioSemicama;
					case ViajeColumn.PrecioCama:
					return entityData.PrecioCama != _originalData.PrecioCama;
					case ViajeColumn.PrecioPromocional:
					return entityData.PrecioPromocional != _originalData.PrecioPromocional;
					case ViajeColumn.FechaPromocion:
					return entityData.FechaPromocion != _originalData.FechaPromocion;
					case ViajeColumn.NDias:
					return entityData.NDias != _originalData.NDias;
					case ViajeColumn.NNoches:
					return entityData.NNoches != _originalData.NNoches;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ViajeColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ViajeId != _originalData.ViajeId;
			result = result || entityData.PaqueteId != _originalData.PaqueteId;
			result = result || entityData.Origen != _originalData.Origen;
			result = result || entityData.FechaSalida != _originalData.FechaSalida;
			result = result || entityData.HoraSalida != _originalData.HoraSalida;
			result = result || entityData.PaisOrigen != _originalData.PaisOrigen;
			result = result || entityData.PaisDestino != _originalData.PaisDestino;
			result = result || entityData.Paso != _originalData.Paso;
			result = result || entityData.Medio != _originalData.Medio;
			result = result || entityData.BusId != _originalData.BusId;
			result = result || entityData.FechaRegreso != _originalData.FechaRegreso;
			result = result || entityData.HoraRegreso != _originalData.HoraRegreso;
			result = result || entityData.Descripcion != _originalData.Descripcion;
			result = result || entityData.PrecioSemicama != _originalData.PrecioSemicama;
			result = result || entityData.PrecioCama != _originalData.PrecioCama;
			result = result || entityData.PrecioPromocional != _originalData.PrecioPromocional;
			result = result || entityData.FechaPromocion != _originalData.FechaPromocion;
			result = result || entityData.NDias != _originalData.NDias;
			result = result || entityData.NNoches != _originalData.NNoches;
			return result;
		}	
		
		///<summary>
		///  Returns a Viaje Entity with the original data.
		///</summary>
		public Viaje GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateViaje(
				_originalData.ViajeId,
				_originalData.PaqueteId,
				_originalData.Origen,
				_originalData.FechaSalida,
				_originalData.HoraSalida,
				_originalData.PaisOrigen,
				_originalData.PaisDestino,
				_originalData.Paso,
				_originalData.Medio,
				_originalData.BusId,
				_originalData.FechaRegreso,
				_originalData.HoraRegreso,
				_originalData.Descripcion,
				_originalData.PrecioSemicama,
				_originalData.PrecioCama,
				_originalData.PrecioPromocional,
				_originalData.FechaPromocion,
				_originalData.NDias,
				_originalData.NNoches
				);
				
			return (Viaje)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ViajeBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ViajeBase)
				return ValueEquals(this, (ViajeBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ViajeBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ViajeId.GetHashCode() ^ 
					((this.PaqueteId == null) ? string.Empty : this.PaqueteId.ToString()).GetHashCode() ^ 
					((this.Origen == null) ? string.Empty : this.Origen.ToString()).GetHashCode() ^ 
					((this.FechaSalida == null) ? string.Empty : this.FechaSalida.ToString()).GetHashCode() ^ 
					((this.HoraSalida == null) ? string.Empty : this.HoraSalida.ToString()).GetHashCode() ^ 
					((this.PaisOrigen == null) ? string.Empty : this.PaisOrigen.ToString()).GetHashCode() ^ 
					((this.PaisDestino == null) ? string.Empty : this.PaisDestino.ToString()).GetHashCode() ^ 
					((this.Paso == null) ? string.Empty : this.Paso.ToString()).GetHashCode() ^ 
					((this.Medio == null) ? string.Empty : this.Medio.ToString()).GetHashCode() ^ 
					((this.BusId == null) ? string.Empty : this.BusId.ToString()).GetHashCode() ^ 
					((this.FechaRegreso == null) ? string.Empty : this.FechaRegreso.ToString()).GetHashCode() ^ 
					((this.HoraRegreso == null) ? string.Empty : this.HoraRegreso.ToString()).GetHashCode() ^ 
					((this.Descripcion == null) ? string.Empty : this.Descripcion.ToString()).GetHashCode() ^ 
					((this.PrecioSemicama == null) ? string.Empty : this.PrecioSemicama.ToString()).GetHashCode() ^ 
					((this.PrecioCama == null) ? string.Empty : this.PrecioCama.ToString()).GetHashCode() ^ 
					((this.PrecioPromocional == null) ? string.Empty : this.PrecioPromocional.ToString()).GetHashCode() ^ 
					((this.FechaPromocion == null) ? string.Empty : this.FechaPromocion.ToString()).GetHashCode() ^ 
					((this.NDias == null) ? string.Empty : this.NDias.ToString()).GetHashCode() ^ 
					((this.NNoches == null) ? string.Empty : this.NNoches.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ViajeBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ViajeBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ViajeBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ViajeBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ViajeBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ViajeBase Object1, ViajeBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ViajeId != Object2.ViajeId)
				equal = false;
			if ( Object1.PaqueteId != null && Object2.PaqueteId != null )
			{
				if (Object1.PaqueteId != Object2.PaqueteId)
					equal = false;
			}
			else if (Object1.PaqueteId == null ^ Object2.PaqueteId == null )
			{
				equal = false;
			}
			if ( Object1.Origen != null && Object2.Origen != null )
			{
				if (Object1.Origen != Object2.Origen)
					equal = false;
			}
			else if (Object1.Origen == null ^ Object2.Origen == null )
			{
				equal = false;
			}
			if ( Object1.FechaSalida != null && Object2.FechaSalida != null )
			{
				if (Object1.FechaSalida != Object2.FechaSalida)
					equal = false;
			}
			else if (Object1.FechaSalida == null ^ Object2.FechaSalida == null )
			{
				equal = false;
			}
			if ( Object1.HoraSalida != null && Object2.HoraSalida != null )
			{
				if (Object1.HoraSalida != Object2.HoraSalida)
					equal = false;
			}
			else if (Object1.HoraSalida == null ^ Object2.HoraSalida == null )
			{
				equal = false;
			}
			if ( Object1.PaisOrigen != null && Object2.PaisOrigen != null )
			{
				if (Object1.PaisOrigen != Object2.PaisOrigen)
					equal = false;
			}
			else if (Object1.PaisOrigen == null ^ Object2.PaisOrigen == null )
			{
				equal = false;
			}
			if ( Object1.PaisDestino != null && Object2.PaisDestino != null )
			{
				if (Object1.PaisDestino != Object2.PaisDestino)
					equal = false;
			}
			else if (Object1.PaisDestino == null ^ Object2.PaisDestino == null )
			{
				equal = false;
			}
			if ( Object1.Paso != null && Object2.Paso != null )
			{
				if (Object1.Paso != Object2.Paso)
					equal = false;
			}
			else if (Object1.Paso == null ^ Object2.Paso == null )
			{
				equal = false;
			}
			if ( Object1.Medio != null && Object2.Medio != null )
			{
				if (Object1.Medio != Object2.Medio)
					equal = false;
			}
			else if (Object1.Medio == null ^ Object2.Medio == null )
			{
				equal = false;
			}
			if ( Object1.BusId != null && Object2.BusId != null )
			{
				if (Object1.BusId != Object2.BusId)
					equal = false;
			}
			else if (Object1.BusId == null ^ Object2.BusId == null )
			{
				equal = false;
			}
			if ( Object1.FechaRegreso != null && Object2.FechaRegreso != null )
			{
				if (Object1.FechaRegreso != Object2.FechaRegreso)
					equal = false;
			}
			else if (Object1.FechaRegreso == null ^ Object2.FechaRegreso == null )
			{
				equal = false;
			}
			if ( Object1.HoraRegreso != null && Object2.HoraRegreso != null )
			{
				if (Object1.HoraRegreso != Object2.HoraRegreso)
					equal = false;
			}
			else if (Object1.HoraRegreso == null ^ Object2.HoraRegreso == null )
			{
				equal = false;
			}
			if ( Object1.Descripcion != null && Object2.Descripcion != null )
			{
				if (Object1.Descripcion != Object2.Descripcion)
					equal = false;
			}
			else if (Object1.Descripcion == null ^ Object2.Descripcion == null )
			{
				equal = false;
			}
			if ( Object1.PrecioSemicama != null && Object2.PrecioSemicama != null )
			{
				if (Object1.PrecioSemicama != Object2.PrecioSemicama)
					equal = false;
			}
			else if (Object1.PrecioSemicama == null ^ Object2.PrecioSemicama == null )
			{
				equal = false;
			}
			if ( Object1.PrecioCama != null && Object2.PrecioCama != null )
			{
				if (Object1.PrecioCama != Object2.PrecioCama)
					equal = false;
			}
			else if (Object1.PrecioCama == null ^ Object2.PrecioCama == null )
			{
				equal = false;
			}
			if ( Object1.PrecioPromocional != null && Object2.PrecioPromocional != null )
			{
				if (Object1.PrecioPromocional != Object2.PrecioPromocional)
					equal = false;
			}
			else if (Object1.PrecioPromocional == null ^ Object2.PrecioPromocional == null )
			{
				equal = false;
			}
			if ( Object1.FechaPromocion != null && Object2.FechaPromocion != null )
			{
				if (Object1.FechaPromocion != Object2.FechaPromocion)
					equal = false;
			}
			else if (Object1.FechaPromocion == null ^ Object2.FechaPromocion == null )
			{
				equal = false;
			}
			if ( Object1.NDias != null && Object2.NDias != null )
			{
				if (Object1.NDias != Object2.NDias)
					equal = false;
			}
			else if (Object1.NDias == null ^ Object2.NDias == null )
			{
				equal = false;
			}
			if ( Object1.NNoches != null && Object2.NNoches != null )
			{
				if (Object1.NNoches != Object2.NNoches)
					equal = false;
			}
			else if (Object1.NNoches == null ^ Object2.NNoches == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ViajeBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ViajeComparer GetComparer()
        {
            return new ViajeComparer();
        }
        */

        // Comparer delegates back to Viaje
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Viaje rhs, ViajeColumn which)
        {
            switch (which)
            {
            	
            	
            	case ViajeColumn.ViajeId:
            		return this.ViajeId.CompareTo(rhs.ViajeId);
            		
            		                 
            	
            	
            	case ViajeColumn.PaqueteId:
            		return this.PaqueteId.Value.CompareTo(rhs.PaqueteId.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.Origen:
            		return this.Origen.CompareTo(rhs.Origen);
            		
            		                 
            	
            	
            	case ViajeColumn.FechaSalida:
            		return this.FechaSalida.Value.CompareTo(rhs.FechaSalida.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.HoraSalida:
            		return this.HoraSalida.CompareTo(rhs.HoraSalida);
            		
            		                 
            	
            	
            	case ViajeColumn.PaisOrigen:
            		return this.PaisOrigen.CompareTo(rhs.PaisOrigen);
            		
            		                 
            	
            	
            	case ViajeColumn.PaisDestino:
            		return this.PaisDestino.CompareTo(rhs.PaisDestino);
            		
            		                 
            	
            	
            	case ViajeColumn.Paso:
            		return this.Paso.CompareTo(rhs.Paso);
            		
            		                 
            	
            	
            	case ViajeColumn.Medio:
            		return this.Medio.CompareTo(rhs.Medio);
            		
            		                 
            	
            	
            	case ViajeColumn.BusId:
            		return this.BusId.Value.CompareTo(rhs.BusId.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.FechaRegreso:
            		return this.FechaRegreso.Value.CompareTo(rhs.FechaRegreso.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.HoraRegreso:
            		return this.HoraRegreso.CompareTo(rhs.HoraRegreso);
            		
            		                 
            	
            	
            	case ViajeColumn.Descripcion:
            		return this.Descripcion.CompareTo(rhs.Descripcion);
            		
            		                 
            	
            	
            	case ViajeColumn.PrecioSemicama:
            		return this.PrecioSemicama.Value.CompareTo(rhs.PrecioSemicama.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.PrecioCama:
            		return this.PrecioCama.Value.CompareTo(rhs.PrecioCama.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.PrecioPromocional:
            		return this.PrecioPromocional.Value.CompareTo(rhs.PrecioPromocional.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.FechaPromocion:
            		return this.FechaPromocion.Value.CompareTo(rhs.FechaPromocion.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.NDias:
            		return this.NDias.Value.CompareTo(rhs.NDias.Value);
            		
            		                 
            	
            	
            	case ViajeColumn.NNoches:
            		return this.NNoches.Value.CompareTo(rhs.NNoches.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ViajeKey> Members
		
		// member variable for the EntityId property
		private ViajeKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ViajeKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ViajeKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Viaje")
					.Append("|").Append( this.ViajeId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{20}{19}- ViajeId: {0}{19}- PaqueteId: {1}{19}- Origen: {2}{19}- FechaSalida: {3}{19}- HoraSalida: {4}{19}- PaisOrigen: {5}{19}- PaisDestino: {6}{19}- Paso: {7}{19}- Medio: {8}{19}- BusId: {9}{19}- FechaRegreso: {10}{19}- HoraRegreso: {11}{19}- Descripcion: {12}{19}- PrecioSemicama: {13}{19}- PrecioCama: {14}{19}- PrecioPromocional: {15}{19}- FechaPromocion: {16}{19}- NDias: {17}{19}- NNoches: {18}{19}{21}", 
				this.ViajeId,
				(this.PaqueteId == null) ? string.Empty : this.PaqueteId.ToString(),
				(this.Origen == null) ? string.Empty : this.Origen.ToString(),
				(this.FechaSalida == null) ? string.Empty : this.FechaSalida.ToString(),
				(this.HoraSalida == null) ? string.Empty : this.HoraSalida.ToString(),
				(this.PaisOrigen == null) ? string.Empty : this.PaisOrigen.ToString(),
				(this.PaisDestino == null) ? string.Empty : this.PaisDestino.ToString(),
				(this.Paso == null) ? string.Empty : this.Paso.ToString(),
				(this.Medio == null) ? string.Empty : this.Medio.ToString(),
				(this.BusId == null) ? string.Empty : this.BusId.ToString(),
				(this.FechaRegreso == null) ? string.Empty : this.FechaRegreso.ToString(),
				(this.HoraRegreso == null) ? string.Empty : this.HoraRegreso.ToString(),
				(this.Descripcion == null) ? string.Empty : this.Descripcion.ToString(),
				(this.PrecioSemicama == null) ? string.Empty : this.PrecioSemicama.ToString(),
				(this.PrecioCama == null) ? string.Empty : this.PrecioCama.ToString(),
				(this.PrecioPromocional == null) ? string.Empty : this.PrecioPromocional.ToString(),
				(this.FechaPromocion == null) ? string.Empty : this.FechaPromocion.ToString(),
				(this.NDias == null) ? string.Empty : this.NDias.ToString(),
				(this.NNoches == null) ? string.Empty : this.NNoches.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Viaje' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ViajeEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ViajeID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Viaje"</remarks>
		public System.Guid ViajeId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalViajeId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// PaqueteID : 
		/// </summary>
		public System.Guid? PaqueteId = null;
		
		/// <summary>
		/// Origen : 
		/// </summary>
		public System.String Origen = null;
		
		/// <summary>
		/// FechaSalida : 
		/// </summary>
		public System.DateTime? FechaSalida = null;
		
		/// <summary>
		/// HoraSalida : 
		/// </summary>
		public System.String HoraSalida = null;
		
		/// <summary>
		/// PaisOrigen : 
		/// </summary>
		public System.String PaisOrigen = null;
		
		/// <summary>
		/// PaisDestino : 
		/// </summary>
		public System.String PaisDestino = null;
		
		/// <summary>
		/// Paso : 
		/// </summary>
		public System.String Paso = null;
		
		/// <summary>
		/// Medio : 
		/// </summary>
		public System.String Medio = null;
		
		/// <summary>
		/// BusID : 
		/// </summary>
		public System.Guid? BusId = null;
		
		/// <summary>
		/// FechaRegreso : 
		/// </summary>
		public System.DateTime? FechaRegreso = null;
		
		/// <summary>
		/// HoraRegreso : 
		/// </summary>
		public System.String HoraRegreso = null;
		
		/// <summary>
		/// Descripcion : 
		/// </summary>
		public System.String Descripcion = null;
		
		/// <summary>
		/// PrecioSemicama : 
		/// </summary>
		public System.Double? PrecioSemicama = null;
		
		/// <summary>
		/// PrecioCama : 
		/// </summary>
		public System.Double? PrecioCama = null;
		
		/// <summary>
		/// PrecioPromocional : 
		/// </summary>
		public System.Double? PrecioPromocional = null;
		
		/// <summary>
		/// FechaPromocion : 
		/// </summary>
		public System.DateTime? FechaPromocion = null;
		
		/// <summary>
		/// nDias : 
		/// </summary>
		public System.Int32? NDias = null;
		
		/// <summary>
		/// nNoches : 
		/// </summary>
		public System.Int32? NNoches = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Paquete _paqueteIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Paquete"/>.
		/// </summary>
		/// <value>The source Paquete for PaqueteId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Paquete PaqueteIdSource
      	{
            get { return this._paqueteIdSource; }
            set { this._paqueteIdSource = value; }
      	}
		private Transporte _busIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Transporte"/>.
		/// </summary>
		/// <value>The source Transporte for BusId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Transporte BusIdSource
      	{
            get { return this._busIdSource; }
            set { this._busIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region PasajeCollection
		
		private TList<Pasaje> _pasajeViajeId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pasajeViajeId
		/// </summary>
		
		public TList<Pasaje> PasajeCollection
		{
			get
			{
				if (_pasajeViajeId == null)
				{
				_pasajeViajeId = new TList<Pasaje>();
				}
	
				return _pasajeViajeId;
			}
			set { _pasajeViajeId = value; }
		}
		
		#endregion

		#region ViajeHotelCollection
		
		private TList<ViajeHotel> _viajeHotelViajeId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _viajeHotelViajeId
		/// </summary>
		
		public TList<ViajeHotel> ViajeHotelCollection
		{
			get
			{
				if (_viajeHotelViajeId == null)
				{
				_viajeHotelViajeId = new TList<ViajeHotel>();
				}
	
				return _viajeHotelViajeId;
			}
			set { _viajeHotelViajeId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ViajeEntityData _tmp = new ViajeEntityData();
						
			_tmp.ViajeId = this.ViajeId;
			_tmp.OriginalViajeId = this.OriginalViajeId;
			
			_tmp.PaqueteId = this.PaqueteId;
			_tmp.Origen = this.Origen;
			_tmp.FechaSalida = this.FechaSalida;
			_tmp.HoraSalida = this.HoraSalida;
			_tmp.PaisOrigen = this.PaisOrigen;
			_tmp.PaisDestino = this.PaisDestino;
			_tmp.Paso = this.Paso;
			_tmp.Medio = this.Medio;
			_tmp.BusId = this.BusId;
			_tmp.FechaRegreso = this.FechaRegreso;
			_tmp.HoraRegreso = this.HoraRegreso;
			_tmp.Descripcion = this.Descripcion;
			_tmp.PrecioSemicama = this.PrecioSemicama;
			_tmp.PrecioCama = this.PrecioCama;
			_tmp.PrecioPromocional = this.PrecioPromocional;
			_tmp.FechaPromocion = this.FechaPromocion;
			_tmp.NDias = this.NDias;
			_tmp.NNoches = this.NNoches;
			
			#region Source Parent Composite Entities
			if (this.PaqueteIdSource != null)
				_tmp.PaqueteIdSource = MakeCopyOf(this.PaqueteIdSource) as Paquete;
			if (this.BusIdSource != null)
				_tmp.BusIdSource = MakeCopyOf(this.BusIdSource) as Transporte;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._pasajeViajeId != null)
				_tmp.PasajeCollection = (TList<Pasaje>) MakeCopyOf(this.PasajeCollection); 
			if (this._viajeHotelViajeId != null)
				_tmp.ViajeHotelCollection = (TList<ViajeHotel>) MakeCopyOf(this.ViajeHotelCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ViajeEntityData _tmp = new ViajeEntityData();
						
			_tmp.ViajeId = this.ViajeId;
			_tmp.OriginalViajeId = this.OriginalViajeId;
			
			_tmp.PaqueteId = this.PaqueteId;
			_tmp.Origen = this.Origen;
			_tmp.FechaSalida = this.FechaSalida;
			_tmp.HoraSalida = this.HoraSalida;
			_tmp.PaisOrigen = this.PaisOrigen;
			_tmp.PaisDestino = this.PaisDestino;
			_tmp.Paso = this.Paso;
			_tmp.Medio = this.Medio;
			_tmp.BusId = this.BusId;
			_tmp.FechaRegreso = this.FechaRegreso;
			_tmp.HoraRegreso = this.HoraRegreso;
			_tmp.Descripcion = this.Descripcion;
			_tmp.PrecioSemicama = this.PrecioSemicama;
			_tmp.PrecioCama = this.PrecioCama;
			_tmp.PrecioPromocional = this.PrecioPromocional;
			_tmp.FechaPromocion = this.FechaPromocion;
			_tmp.NDias = this.NDias;
			_tmp.NNoches = this.NNoches;
			
			#region Source Parent Composite Entities
			if (this.PaqueteIdSource != null && existingCopies.Contains(this.PaqueteIdSource))
				_tmp.PaqueteIdSource = existingCopies[this.PaqueteIdSource] as Paquete;
			else
				_tmp.PaqueteIdSource = MakeCopyOf(this.PaqueteIdSource, existingCopies) as Paquete;
			if (this.BusIdSource != null && existingCopies.Contains(this.BusIdSource))
				_tmp.BusIdSource = existingCopies[this.BusIdSource] as Transporte;
			else
				_tmp.BusIdSource = MakeCopyOf(this.BusIdSource, existingCopies) as Transporte;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.PasajeCollection = (TList<Pasaje>) MakeCopyOf(this.PasajeCollection, existingCopies); 
			_tmp.ViajeHotelCollection = (TList<ViajeHotel>) MakeCopyOf(this.ViajeHotelCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ViajeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ViajeColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ViajeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ViajeColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ViajeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ViajeColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				ViajeEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ViajeEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ViajeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ViajeColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ViajeEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ViajeEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ViajeEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Viaje"/> object.
	/// </remarks>
	public class ViajeEventArgs : System.EventArgs
	{
		private ViajeColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ViajeEventArgs class.
		///</summary>
		public ViajeEventArgs(ViajeColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ViajeEventArgs class.
		///</summary>
		public ViajeEventArgs(ViajeColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ViajeColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ViajeColumn" />
		public ViajeColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Viaje related events.
	///</summary>
	public delegate void ViajeEventHandler(object sender, ViajeEventArgs e);
	
	#region ViajeComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ViajeComparer : System.Collections.Generic.IComparer<Viaje>
	{
		ViajeColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ViajeComparer"/> class.
        /// </summary>
		public ViajeComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ViajeComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ViajeComparer(ViajeColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Viaje"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Viaje"/> to compare.</param>
        /// <param name="b">The second <c>Viaje</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Viaje a, Viaje b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Viaje entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Viaje a, Viaje b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ViajeColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ViajeKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Viaje"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ViajeKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ViajeKey class.
		/// </summary>
		public ViajeKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ViajeKey class.
		/// </summary>
		public ViajeKey(ViajeBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ViajeId = entity.ViajeId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ViajeKey class.
		/// </summary>
		public ViajeKey(System.Guid _viajeId)
		{
			#region Init Properties

			this.ViajeId = _viajeId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ViajeBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ViajeBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ViajeId property
		private System.Guid _viajeId;
		
		/// <summary>
		/// Gets or sets the ViajeId property.
		/// </summary>
		public System.Guid ViajeId
		{
			get { return _viajeId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ViajeId = value;
				
				_viajeId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ViajeId = ( values["ViajeId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["ViajeId"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ViajeId", ViajeId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ViajeId: {0}{1}",
								ViajeId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ViajeColumn Enum
	
	/// <summary>
	/// Enumerate the Viaje columns.
	/// </summary>
	[Serializable]
	public enum ViajeColumn : int
	{
		/// <summary>
		/// ViajeId : 
		/// </summary>
		[EnumTextValue("ViajeID")]
		[ColumnEnum("ViajeID", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		ViajeId = 1,
		/// <summary>
		/// PaqueteId : 
		/// </summary>
		[EnumTextValue("PaqueteID")]
		[ColumnEnum("PaqueteID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
		PaqueteId = 2,
		/// <summary>
		/// Origen : 
		/// </summary>
		[EnumTextValue("Origen")]
		[ColumnEnum("Origen", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Origen = 3,
		/// <summary>
		/// FechaSalida : 
		/// </summary>
		[EnumTextValue("FechaSalida")]
		[ColumnEnum("FechaSalida", typeof(System.DateTime), System.Data.DbType.Date, false, false, true)]
		FechaSalida = 4,
		/// <summary>
		/// HoraSalida : 
		/// </summary>
		[EnumTextValue("HoraSalida")]
		[ColumnEnum("HoraSalida", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		HoraSalida = 5,
		/// <summary>
		/// PaisOrigen : 
		/// </summary>
		[EnumTextValue("PaisOrigen")]
		[ColumnEnum("PaisOrigen", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		PaisOrigen = 6,
		/// <summary>
		/// PaisDestino : 
		/// </summary>
		[EnumTextValue("PaisDestino")]
		[ColumnEnum("PaisDestino", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		PaisDestino = 7,
		/// <summary>
		/// Paso : 
		/// </summary>
		[EnumTextValue("Paso")]
		[ColumnEnum("Paso", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Paso = 8,
		/// <summary>
		/// Medio : 
		/// </summary>
		[EnumTextValue("Medio")]
		[ColumnEnum("Medio", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Medio = 9,
		/// <summary>
		/// BusId : 
		/// </summary>
		[EnumTextValue("BusID")]
		[ColumnEnum("BusID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
		BusId = 10,
		/// <summary>
		/// FechaRegreso : 
		/// </summary>
		[EnumTextValue("FechaRegreso")]
		[ColumnEnum("FechaRegreso", typeof(System.DateTime), System.Data.DbType.Date, false, false, true)]
		FechaRegreso = 11,
		/// <summary>
		/// HoraRegreso : 
		/// </summary>
		[EnumTextValue("HoraRegreso")]
		[ColumnEnum("HoraRegreso", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		HoraRegreso = 12,
		/// <summary>
		/// Descripcion : 
		/// </summary>
		[EnumTextValue("Descripcion")]
		[ColumnEnum("Descripcion", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 200)]
		Descripcion = 13,
		/// <summary>
		/// PrecioSemicama : 
		/// </summary>
		[EnumTextValue("PrecioSemicama")]
		[ColumnEnum("PrecioSemicama", typeof(System.Double), System.Data.DbType.Double, false, false, true)]
		PrecioSemicama = 14,
		/// <summary>
		/// PrecioCama : 
		/// </summary>
		[EnumTextValue("PrecioCama")]
		[ColumnEnum("PrecioCama", typeof(System.Double), System.Data.DbType.Double, false, false, true)]
		PrecioCama = 15,
		/// <summary>
		/// PrecioPromocional : 
		/// </summary>
		[EnumTextValue("PrecioPromocional")]
		[ColumnEnum("PrecioPromocional", typeof(System.Double), System.Data.DbType.Double, false, false, true)]
		PrecioPromocional = 16,
		/// <summary>
		/// FechaPromocion : 
		/// </summary>
		[EnumTextValue("FechaPromocion")]
		[ColumnEnum("FechaPromocion", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		FechaPromocion = 17,
		/// <summary>
		/// NDias : 
		/// </summary>
		[EnumTextValue("nDias")]
		[ColumnEnum("nDias", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		NDias = 18,
		/// <summary>
		/// NNoches : 
		/// </summary>
		[EnumTextValue("nNoches")]
		[ColumnEnum("nNoches", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		NNoches = 19
	}//End enum

	#endregion ViajeColumn Enum

} // end namespace
