/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PersonaProveedor.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace MAT.Entities
{
	///<summary>
	/// An object representation of the 'PersonaProveedor' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("PersonaProveedorBase")]
	public abstract partial class PersonaProveedorBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// PersonaID : 
		/// </summary>
		private System.Guid		  _personaId = Guid.Empty;
		
		/// <summary>
		/// Apellido : 
		/// </summary>
		private System.String		  _apellido = null;
		
		/// <summary>
		/// Nombre : 
		/// </summary>
		private System.String		  _nombre = null;
		
		/// <summary>
		/// NroDocumento : 
		/// </summary>
		private System.String		  _nroDocumento = null;
		
		/// <summary>
		/// LocalidadID : 
		/// </summary>
		private System.Int32?		  _localidadId = null;
		
		/// <summary>
		/// Telefono : 
		/// </summary>
		private System.String		  _telefono = null;
		
		/// <summary>
		/// Email : 
		/// </summary>
		private System.String		  _email = null;
		
		/// <summary>
		/// FechaNacimiento : 
		/// </summary>
		private System.DateTime?		  _fechaNacimiento = null;
		
		/// <summary>
		/// Sexo : 
		/// </summary>
		private System.Int32?		  _sexo = null;
		
		/// <summary>
		/// Domicilio : 
		/// </summary>
		private System.String		  _domicilio = null;
		
		/// <summary>
		/// ProveedorID : 
		/// </summary>
		private System.Guid		  _proveedorId = Guid.Empty;
		
		/// <summary>
		/// RazonSocial : 
		/// </summary>
		private System.String		  _razonSocial = null;
		
		/// <summary>
		/// ProveedorLocalidadID : 
		/// </summary>
		private System.Int32?		  _proveedorLocalidadId = null;
		
		/// <summary>
		/// ProveedorTelefono : 
		/// </summary>
		private System.String		  _proveedorTelefono = null;
		
		/// <summary>
		/// Fax : 
		/// </summary>
		private System.String		  _fax = null;
		
		/// <summary>
		/// Web : 
		/// </summary>
		private System.String		  _web = null;
		
		/// <summary>
		/// ProveedorEmail : 
		/// </summary>
		private System.String		  _proveedorEmail = null;
		
		/// <summary>
		/// Idioma : 
		/// </summary>
		private System.String		  _idioma = null;
		
		/// <summary>
		/// CondicionIva : 
		/// </summary>
		private System.Int32?		  _condicionIva = null;
		
		/// <summary>
		/// Cuit : 
		/// </summary>
		private System.String		  _cuit = null;
		
		/// <summary>
		/// FormaPago : 
		/// </summary>
		private System.Int32?		  _formaPago = null;
		
		/// <summary>
		/// TipoDocumento : 
		/// </summary>
		private System.Int32?		  _tipoDocumento = null;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PersonaProveedorBase"/> instance.
		///</summary>
		public PersonaProveedorBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="PersonaProveedorBase"/> instance.
		///</summary>
		///<param name="_personaId"></param>
		///<param name="_apellido"></param>
		///<param name="_nombre"></param>
		///<param name="_nroDocumento"></param>
		///<param name="_localidadId"></param>
		///<param name="_telefono"></param>
		///<param name="_email"></param>
		///<param name="_fechaNacimiento"></param>
		///<param name="_sexo"></param>
		///<param name="_domicilio"></param>
		///<param name="_proveedorId"></param>
		///<param name="_razonSocial"></param>
		///<param name="_proveedorLocalidadId"></param>
		///<param name="_proveedorTelefono"></param>
		///<param name="_fax"></param>
		///<param name="_web"></param>
		///<param name="_proveedorEmail"></param>
		///<param name="_idioma"></param>
		///<param name="_condicionIva"></param>
		///<param name="_cuit"></param>
		///<param name="_formaPago"></param>
		///<param name="_tipoDocumento"></param>
		public PersonaProveedorBase(System.Guid _personaId, System.String _apellido, System.String _nombre, System.String _nroDocumento, System.Int32? _localidadId, System.String _telefono, System.String _email, System.DateTime? _fechaNacimiento, System.Int32? _sexo, System.String _domicilio, System.Guid _proveedorId, System.String _razonSocial, System.Int32? _proveedorLocalidadId, System.String _proveedorTelefono, System.String _fax, System.String _web, System.String _proveedorEmail, System.String _idioma, System.Int32? _condicionIva, System.String _cuit, System.Int32? _formaPago, System.Int32? _tipoDocumento)
		{
			this._personaId = _personaId;
			this._apellido = _apellido;
			this._nombre = _nombre;
			this._nroDocumento = _nroDocumento;
			this._localidadId = _localidadId;
			this._telefono = _telefono;
			this._email = _email;
			this._fechaNacimiento = _fechaNacimiento;
			this._sexo = _sexo;
			this._domicilio = _domicilio;
			this._proveedorId = _proveedorId;
			this._razonSocial = _razonSocial;
			this._proveedorLocalidadId = _proveedorLocalidadId;
			this._proveedorTelefono = _proveedorTelefono;
			this._fax = _fax;
			this._web = _web;
			this._proveedorEmail = _proveedorEmail;
			this._idioma = _idioma;
			this._condicionIva = _condicionIva;
			this._cuit = _cuit;
			this._formaPago = _formaPago;
			this._tipoDocumento = _tipoDocumento;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PersonaProveedor"/> instance.
		///</summary>
		///<param name="_personaId"></param>
		///<param name="_apellido"></param>
		///<param name="_nombre"></param>
		///<param name="_nroDocumento"></param>
		///<param name="_localidadId"></param>
		///<param name="_telefono"></param>
		///<param name="_email"></param>
		///<param name="_fechaNacimiento"></param>
		///<param name="_sexo"></param>
		///<param name="_domicilio"></param>
		///<param name="_proveedorId"></param>
		///<param name="_razonSocial"></param>
		///<param name="_proveedorLocalidadId"></param>
		///<param name="_proveedorTelefono"></param>
		///<param name="_fax"></param>
		///<param name="_web"></param>
		///<param name="_proveedorEmail"></param>
		///<param name="_idioma"></param>
		///<param name="_condicionIva"></param>
		///<param name="_cuit"></param>
		///<param name="_formaPago"></param>
		///<param name="_tipoDocumento"></param>
		public static PersonaProveedor CreatePersonaProveedor(System.Guid _personaId, System.String _apellido, System.String _nombre, System.String _nroDocumento, System.Int32? _localidadId, System.String _telefono, System.String _email, System.DateTime? _fechaNacimiento, System.Int32? _sexo, System.String _domicilio, System.Guid _proveedorId, System.String _razonSocial, System.Int32? _proveedorLocalidadId, System.String _proveedorTelefono, System.String _fax, System.String _web, System.String _proveedorEmail, System.String _idioma, System.Int32? _condicionIva, System.String _cuit, System.Int32? _formaPago, System.Int32? _tipoDocumento)
		{
			PersonaProveedor newPersonaProveedor = new PersonaProveedor();
			newPersonaProveedor.PersonaId = _personaId;
			newPersonaProveedor.Apellido = _apellido;
			newPersonaProveedor.Nombre = _nombre;
			newPersonaProveedor.NroDocumento = _nroDocumento;
			newPersonaProveedor.LocalidadId = _localidadId;
			newPersonaProveedor.Telefono = _telefono;
			newPersonaProveedor.Email = _email;
			newPersonaProveedor.FechaNacimiento = _fechaNacimiento;
			newPersonaProveedor.Sexo = _sexo;
			newPersonaProveedor.Domicilio = _domicilio;
			newPersonaProveedor.ProveedorId = _proveedorId;
			newPersonaProveedor.RazonSocial = _razonSocial;
			newPersonaProveedor.ProveedorLocalidadId = _proveedorLocalidadId;
			newPersonaProveedor.ProveedorTelefono = _proveedorTelefono;
			newPersonaProveedor.Fax = _fax;
			newPersonaProveedor.Web = _web;
			newPersonaProveedor.ProveedorEmail = _proveedorEmail;
			newPersonaProveedor.Idioma = _idioma;
			newPersonaProveedor.CondicionIva = _condicionIva;
			newPersonaProveedor.Cuit = _cuit;
			newPersonaProveedor.FormaPago = _formaPago;
			newPersonaProveedor.TipoDocumento = _tipoDocumento;
			return newPersonaProveedor;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the PersonaID property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Guid PersonaId
		{
			get
			{
				return this._personaId; 
			}
			set
			{
				if (_personaId == value)
					return;
					
				this._personaId = value;
				this._isDirty = true;
				
				OnPropertyChanged("PersonaId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Apellido property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Apellido
		{
			get
			{
				return this._apellido; 
			}
			set
			{
				if (_apellido == value)
					return;
					
				this._apellido = value;
				this._isDirty = true;
				
				OnPropertyChanged("Apellido");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Nombre property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Nombre
		{
			get
			{
				return this._nombre; 
			}
			set
			{
				if (_nombre == value)
					return;
					
				this._nombre = value;
				this._isDirty = true;
				
				OnPropertyChanged("Nombre");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the NroDocumento property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String NroDocumento
		{
			get
			{
				return this._nroDocumento; 
			}
			set
			{
				if (_nroDocumento == value)
					return;
					
				this._nroDocumento = value;
				this._isDirty = true;
				
				OnPropertyChanged("NroDocumento");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LocalidadID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsLocalidadIdNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? LocalidadId
		{
			get
			{
				return this._localidadId; 
			}
			set
			{
				if (_localidadId == value && LocalidadId != null )
					return;
					
				this._localidadId = value;
				this._isDirty = true;
				
				OnPropertyChanged("LocalidadId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Telefono property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Telefono
		{
			get
			{
				return this._telefono; 
			}
			set
			{
				if (_telefono == value)
					return;
					
				this._telefono = value;
				this._isDirty = true;
				
				OnPropertyChanged("Telefono");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Email property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Email
		{
			get
			{
				return this._email; 
			}
			set
			{
				if (_email == value)
					return;
					
				this._email = value;
				this._isDirty = true;
				
				OnPropertyChanged("Email");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the FechaNacimiento property. 
		///		
		/// </summary>
		/// <value>This type is date</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsFechaNacimientoNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime? FechaNacimiento
		{
			get
			{
				return this._fechaNacimiento; 
			}
			set
			{
				if (_fechaNacimiento == value && FechaNacimiento != null )
					return;
					
				this._fechaNacimiento = value;
				this._isDirty = true;
				
				OnPropertyChanged("FechaNacimiento");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Sexo property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsSexoNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? Sexo
		{
			get
			{
				return this._sexo; 
			}
			set
			{
				if (_sexo == value && Sexo != null )
					return;
					
				this._sexo = value;
				this._isDirty = true;
				
				OnPropertyChanged("Sexo");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Domicilio property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Domicilio
		{
			get
			{
				return this._domicilio; 
			}
			set
			{
				if (_domicilio == value)
					return;
					
				this._domicilio = value;
				this._isDirty = true;
				
				OnPropertyChanged("Domicilio");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProveedorID property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Guid ProveedorId
		{
			get
			{
				return this._proveedorId; 
			}
			set
			{
				if (_proveedorId == value)
					return;
					
				this._proveedorId = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProveedorId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the RazonSocial property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String RazonSocial
		{
			get
			{
				return this._razonSocial; 
			}
			set
			{
				if (_razonSocial == value)
					return;
					
				this._razonSocial = value;
				this._isDirty = true;
				
				OnPropertyChanged("RazonSocial");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProveedorLocalidadID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsProveedorLocalidadIdNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? ProveedorLocalidadId
		{
			get
			{
				return this._proveedorLocalidadId; 
			}
			set
			{
				if (_proveedorLocalidadId == value && ProveedorLocalidadId != null )
					return;
					
				this._proveedorLocalidadId = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProveedorLocalidadId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProveedorTelefono property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ProveedorTelefono
		{
			get
			{
				return this._proveedorTelefono; 
			}
			set
			{
				if (_proveedorTelefono == value)
					return;
					
				this._proveedorTelefono = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProveedorTelefono");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Fax property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Fax
		{
			get
			{
				return this._fax; 
			}
			set
			{
				if (_fax == value)
					return;
					
				this._fax = value;
				this._isDirty = true;
				
				OnPropertyChanged("Fax");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Web property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Web
		{
			get
			{
				return this._web; 
			}
			set
			{
				if (_web == value)
					return;
					
				this._web = value;
				this._isDirty = true;
				
				OnPropertyChanged("Web");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProveedorEmail property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ProveedorEmail
		{
			get
			{
				return this._proveedorEmail; 
			}
			set
			{
				if (_proveedorEmail == value)
					return;
					
				this._proveedorEmail = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProveedorEmail");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Idioma property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Idioma
		{
			get
			{
				return this._idioma; 
			}
			set
			{
				if (_idioma == value)
					return;
					
				this._idioma = value;
				this._isDirty = true;
				
				OnPropertyChanged("Idioma");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the CondicionIva property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsCondicionIvaNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? CondicionIva
		{
			get
			{
				return this._condicionIva; 
			}
			set
			{
				if (_condicionIva == value && CondicionIva != null )
					return;
					
				this._condicionIva = value;
				this._isDirty = true;
				
				OnPropertyChanged("CondicionIva");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Cuit property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Cuit
		{
			get
			{
				return this._cuit; 
			}
			set
			{
				if (_cuit == value)
					return;
					
				this._cuit = value;
				this._isDirty = true;
				
				OnPropertyChanged("Cuit");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the FormaPago property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsFormaPagoNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? FormaPago
		{
			get
			{
				return this._formaPago; 
			}
			set
			{
				if (_formaPago == value && FormaPago != null )
					return;
					
				this._formaPago = value;
				this._isDirty = true;
				
				OnPropertyChanged("FormaPago");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TipoDocumento property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsTipoDocumentoNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? TipoDocumento
		{
			get
			{
				return this._tipoDocumento; 
			}
			set
			{
				if (_tipoDocumento == value && TipoDocumento != null )
					return;
					
				this._tipoDocumento = value;
				this._isDirty = true;
				
				OnPropertyChanged("TipoDocumento");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "PersonaProveedor"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PersonaProveedorBase Entity 
		///</summary>
		public virtual PersonaProveedorBase Copy()
		{
			//shallow copy entity
			PersonaProveedor copy = new PersonaProveedor();
				copy.PersonaId = this.PersonaId;
				copy.Apellido = this.Apellido;
				copy.Nombre = this.Nombre;
				copy.NroDocumento = this.NroDocumento;
				copy.LocalidadId = this.LocalidadId;
				copy.Telefono = this.Telefono;
				copy.Email = this.Email;
				copy.FechaNacimiento = this.FechaNacimiento;
				copy.Sexo = this.Sexo;
				copy.Domicilio = this.Domicilio;
				copy.ProveedorId = this.ProveedorId;
				copy.RazonSocial = this.RazonSocial;
				copy.ProveedorLocalidadId = this.ProveedorLocalidadId;
				copy.ProveedorTelefono = this.ProveedorTelefono;
				copy.Fax = this.Fax;
				copy.Web = this.Web;
				copy.ProveedorEmail = this.ProveedorEmail;
				copy.Idioma = this.Idioma;
				copy.CondicionIva = this.CondicionIva;
				copy.Cuit = this.Cuit;
				copy.FormaPago = this.FormaPago;
				copy.TipoDocumento = this.TipoDocumento;
			copy.AcceptChanges();
			return (PersonaProveedor)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PersonaProveedorBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PersonaProveedorBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="PersonaProveedorBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="PersonaProveedorBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PersonaProveedorBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(PersonaProveedorBase Object1, PersonaProveedorBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.PersonaId != Object2.PersonaId)
				equal = false;
			if (Object1.Apellido != null && Object2.Apellido != null )
			{
				if (Object1.Apellido != Object2.Apellido)
					equal = false;
			}
			else if (Object1.Apellido == null ^ Object1.Apellido == null )
			{
				equal = false;
			}
			if (Object1.Nombre != null && Object2.Nombre != null )
			{
				if (Object1.Nombre != Object2.Nombre)
					equal = false;
			}
			else if (Object1.Nombre == null ^ Object1.Nombre == null )
			{
				equal = false;
			}
			if (Object1.NroDocumento != null && Object2.NroDocumento != null )
			{
				if (Object1.NroDocumento != Object2.NroDocumento)
					equal = false;
			}
			else if (Object1.NroDocumento == null ^ Object1.NroDocumento == null )
			{
				equal = false;
			}
			if (Object1.LocalidadId != null && Object2.LocalidadId != null )
			{
				if (Object1.LocalidadId != Object2.LocalidadId)
					equal = false;
			}
			else if (Object1.LocalidadId == null ^ Object1.LocalidadId == null )
			{
				equal = false;
			}
			if (Object1.Telefono != null && Object2.Telefono != null )
			{
				if (Object1.Telefono != Object2.Telefono)
					equal = false;
			}
			else if (Object1.Telefono == null ^ Object1.Telefono == null )
			{
				equal = false;
			}
			if (Object1.Email != null && Object2.Email != null )
			{
				if (Object1.Email != Object2.Email)
					equal = false;
			}
			else if (Object1.Email == null ^ Object1.Email == null )
			{
				equal = false;
			}
			if (Object1.FechaNacimiento != null && Object2.FechaNacimiento != null )
			{
				if (Object1.FechaNacimiento != Object2.FechaNacimiento)
					equal = false;
			}
			else if (Object1.FechaNacimiento == null ^ Object1.FechaNacimiento == null )
			{
				equal = false;
			}
			if (Object1.Sexo != null && Object2.Sexo != null )
			{
				if (Object1.Sexo != Object2.Sexo)
					equal = false;
			}
			else if (Object1.Sexo == null ^ Object1.Sexo == null )
			{
				equal = false;
			}
			if (Object1.Domicilio != null && Object2.Domicilio != null )
			{
				if (Object1.Domicilio != Object2.Domicilio)
					equal = false;
			}
			else if (Object1.Domicilio == null ^ Object1.Domicilio == null )
			{
				equal = false;
			}
			if (Object1.ProveedorId != Object2.ProveedorId)
				equal = false;
			if (Object1.RazonSocial != null && Object2.RazonSocial != null )
			{
				if (Object1.RazonSocial != Object2.RazonSocial)
					equal = false;
			}
			else if (Object1.RazonSocial == null ^ Object1.RazonSocial == null )
			{
				equal = false;
			}
			if (Object1.ProveedorLocalidadId != null && Object2.ProveedorLocalidadId != null )
			{
				if (Object1.ProveedorLocalidadId != Object2.ProveedorLocalidadId)
					equal = false;
			}
			else if (Object1.ProveedorLocalidadId == null ^ Object1.ProveedorLocalidadId == null )
			{
				equal = false;
			}
			if (Object1.ProveedorTelefono != null && Object2.ProveedorTelefono != null )
			{
				if (Object1.ProveedorTelefono != Object2.ProveedorTelefono)
					equal = false;
			}
			else if (Object1.ProveedorTelefono == null ^ Object1.ProveedorTelefono == null )
			{
				equal = false;
			}
			if (Object1.Fax != null && Object2.Fax != null )
			{
				if (Object1.Fax != Object2.Fax)
					equal = false;
			}
			else if (Object1.Fax == null ^ Object1.Fax == null )
			{
				equal = false;
			}
			if (Object1.Web != null && Object2.Web != null )
			{
				if (Object1.Web != Object2.Web)
					equal = false;
			}
			else if (Object1.Web == null ^ Object1.Web == null )
			{
				equal = false;
			}
			if (Object1.ProveedorEmail != null && Object2.ProveedorEmail != null )
			{
				if (Object1.ProveedorEmail != Object2.ProveedorEmail)
					equal = false;
			}
			else if (Object1.ProveedorEmail == null ^ Object1.ProveedorEmail == null )
			{
				equal = false;
			}
			if (Object1.Idioma != null && Object2.Idioma != null )
			{
				if (Object1.Idioma != Object2.Idioma)
					equal = false;
			}
			else if (Object1.Idioma == null ^ Object1.Idioma == null )
			{
				equal = false;
			}
			if (Object1.CondicionIva != null && Object2.CondicionIva != null )
			{
				if (Object1.CondicionIva != Object2.CondicionIva)
					equal = false;
			}
			else if (Object1.CondicionIva == null ^ Object1.CondicionIva == null )
			{
				equal = false;
			}
			if (Object1.Cuit != null && Object2.Cuit != null )
			{
				if (Object1.Cuit != Object2.Cuit)
					equal = false;
			}
			else if (Object1.Cuit == null ^ Object1.Cuit == null )
			{
				equal = false;
			}
			if (Object1.FormaPago != null && Object2.FormaPago != null )
			{
				if (Object1.FormaPago != Object2.FormaPago)
					equal = false;
			}
			else if (Object1.FormaPago == null ^ Object1.FormaPago == null )
			{
				equal = false;
			}
			if (Object1.TipoDocumento != null && Object2.TipoDocumento != null )
			{
				if (Object1.TipoDocumento != Object2.TipoDocumento)
					equal = false;
			}
			else if (Object1.TipoDocumento == null ^ Object1.TipoDocumento == null )
			{
				equal = false;
			}
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(PersonaProveedor entity, string propertyName)
		{
			switch (propertyName)
			{
				case "PersonaId":
					return entity.PersonaId;
				case "Apellido":
					return entity.Apellido;
				case "Nombre":
					return entity.Nombre;
				case "NroDocumento":
					return entity.NroDocumento;
				case "LocalidadId":
					return entity.LocalidadId;
				case "Telefono":
					return entity.Telefono;
				case "Email":
					return entity.Email;
				case "FechaNacimiento":
					return entity.FechaNacimiento;
				case "Sexo":
					return entity.Sexo;
				case "Domicilio":
					return entity.Domicilio;
				case "ProveedorId":
					return entity.ProveedorId;
				case "RazonSocial":
					return entity.RazonSocial;
				case "ProveedorLocalidadId":
					return entity.ProveedorLocalidadId;
				case "ProveedorTelefono":
					return entity.ProveedorTelefono;
				case "Fax":
					return entity.Fax;
				case "Web":
					return entity.Web;
				case "ProveedorEmail":
					return entity.ProveedorEmail;
				case "Idioma":
					return entity.Idioma;
				case "CondicionIva":
					return entity.CondicionIva;
				case "Cuit":
					return entity.Cuit;
				case "FormaPago":
					return entity.FormaPago;
				case "TipoDocumento":
					return entity.TipoDocumento;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as PersonaProveedor, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{23}{22}- PersonaId: {0}{22}- Apellido: {1}{22}- Nombre: {2}{22}- NroDocumento: {3}{22}- LocalidadId: {4}{22}- Telefono: {5}{22}- Email: {6}{22}- FechaNacimiento: {7}{22}- Sexo: {8}{22}- Domicilio: {9}{22}- ProveedorId: {10}{22}- RazonSocial: {11}{22}- ProveedorLocalidadId: {12}{22}- ProveedorTelefono: {13}{22}- Fax: {14}{22}- Web: {15}{22}- ProveedorEmail: {16}{22}- Idioma: {17}{22}- CondicionIva: {18}{22}- Cuit: {19}{22}- FormaPago: {20}{22}- TipoDocumento: {21}{22}", 
				this.PersonaId,
				(this.Apellido == null) ? string.Empty : this.Apellido.ToString(),
			     
				(this.Nombre == null) ? string.Empty : this.Nombre.ToString(),
			     
				(this.NroDocumento == null) ? string.Empty : this.NroDocumento.ToString(),
			     
				(this.LocalidadId == null) ? string.Empty : this.LocalidadId.ToString(),
			     
				(this.Telefono == null) ? string.Empty : this.Telefono.ToString(),
			     
				(this.Email == null) ? string.Empty : this.Email.ToString(),
			     
				(this.FechaNacimiento == null) ? string.Empty : this.FechaNacimiento.ToString(),
			     
				(this.Sexo == null) ? string.Empty : this.Sexo.ToString(),
			     
				(this.Domicilio == null) ? string.Empty : this.Domicilio.ToString(),
			     
				this.ProveedorId,
				(this.RazonSocial == null) ? string.Empty : this.RazonSocial.ToString(),
			     
				(this.ProveedorLocalidadId == null) ? string.Empty : this.ProveedorLocalidadId.ToString(),
			     
				(this.ProveedorTelefono == null) ? string.Empty : this.ProveedorTelefono.ToString(),
			     
				(this.Fax == null) ? string.Empty : this.Fax.ToString(),
			     
				(this.Web == null) ? string.Empty : this.Web.ToString(),
			     
				(this.ProveedorEmail == null) ? string.Empty : this.ProveedorEmail.ToString(),
			     
				(this.Idioma == null) ? string.Empty : this.Idioma.ToString(),
			     
				(this.CondicionIva == null) ? string.Empty : this.CondicionIva.ToString(),
			     
				(this.Cuit == null) ? string.Empty : this.Cuit.ToString(),
			     
				(this.FormaPago == null) ? string.Empty : this.FormaPago.ToString(),
			     
				(this.TipoDocumento == null) ? string.Empty : this.TipoDocumento.ToString(),
			     
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the PersonaProveedor columns.
	/// </summary>
	[Serializable]
	public enum PersonaProveedorColumn
	{
		/// <summary>
		/// PersonaID : 
		/// </summary>
		[EnumTextValue("PersonaID")]
		[ColumnEnum("PersonaID", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		PersonaId,
		/// <summary>
		/// Apellido : 
		/// </summary>
		[EnumTextValue("Apellido")]
		[ColumnEnum("Apellido", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 100)]
		Apellido,
		/// <summary>
		/// Nombre : 
		/// </summary>
		[EnumTextValue("Nombre")]
		[ColumnEnum("Nombre", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 100)]
		Nombre,
		/// <summary>
		/// NroDocumento : 
		/// </summary>
		[EnumTextValue("NroDocumento")]
		[ColumnEnum("NroDocumento", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		NroDocumento,
		/// <summary>
		/// LocalidadID : 
		/// </summary>
		[EnumTextValue("LocalidadID")]
		[ColumnEnum("LocalidadID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		LocalidadId,
		/// <summary>
		/// Telefono : 
		/// </summary>
		[EnumTextValue("Telefono")]
		[ColumnEnum("Telefono", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Telefono,
		/// <summary>
		/// Email : 
		/// </summary>
		[EnumTextValue("Email")]
		[ColumnEnum("Email", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Email,
		/// <summary>
		/// FechaNacimiento : 
		/// </summary>
		[EnumTextValue("FechaNacimiento")]
		[ColumnEnum("FechaNacimiento", typeof(System.DateTime), System.Data.DbType.Date, false, false, true)]
		FechaNacimiento,
		/// <summary>
		/// Sexo : 
		/// </summary>
		[EnumTextValue("Sexo")]
		[ColumnEnum("Sexo", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Sexo,
		/// <summary>
		/// Domicilio : 
		/// </summary>
		[EnumTextValue("Domicilio")]
		[ColumnEnum("Domicilio", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 100)]
		Domicilio,
		/// <summary>
		/// ProveedorID : 
		/// </summary>
		[EnumTextValue("ProveedorID")]
		[ColumnEnum("ProveedorID", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		ProveedorId,
		/// <summary>
		/// RazonSocial : 
		/// </summary>
		[EnumTextValue("RazonSocial")]
		[ColumnEnum("RazonSocial", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		RazonSocial,
		/// <summary>
		/// ProveedorLocalidadID : 
		/// </summary>
		[EnumTextValue("ProveedorLocalidadID")]
		[ColumnEnum("ProveedorLocalidadID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ProveedorLocalidadId,
		/// <summary>
		/// ProveedorTelefono : 
		/// </summary>
		[EnumTextValue("ProveedorTelefono")]
		[ColumnEnum("ProveedorTelefono", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		ProveedorTelefono,
		/// <summary>
		/// Fax : 
		/// </summary>
		[EnumTextValue("Fax")]
		[ColumnEnum("Fax", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Fax,
		/// <summary>
		/// Web : 
		/// </summary>
		[EnumTextValue("Web")]
		[ColumnEnum("Web", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Web,
		/// <summary>
		/// ProveedorEmail : 
		/// </summary>
		[EnumTextValue("ProveedorEmail")]
		[ColumnEnum("ProveedorEmail", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		ProveedorEmail,
		/// <summary>
		/// Idioma : 
		/// </summary>
		[EnumTextValue("Idioma")]
		[ColumnEnum("Idioma", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Idioma,
		/// <summary>
		/// CondicionIva : 
		/// </summary>
		[EnumTextValue("CondicionIva")]
		[ColumnEnum("CondicionIva", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CondicionIva,
		/// <summary>
		/// Cuit : 
		/// </summary>
		[EnumTextValue("Cuit")]
		[ColumnEnum("Cuit", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Cuit,
		/// <summary>
		/// FormaPago : 
		/// </summary>
		[EnumTextValue("FormaPago")]
		[ColumnEnum("FormaPago", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		FormaPago,
		/// <summary>
		/// TipoDocumento : 
		/// </summary>
		[EnumTextValue("TipoDocumento")]
		[ColumnEnum("TipoDocumento", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		TipoDocumento
	}//End enum

} // end namespace
