/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file MAT.Entities.PlanillaServicio.cs instead.
*/

#region Using directives

using System;
using System.Data;
using System.Collections;
using System.Diagnostics;
using System.Web.Services.Protocols;
using MAT.Entities;
using MAT.Data.Bases;

#endregion

namespace MAT.Data.WebServiceClient
{

	///<summary>
	/// This class is the webservice client implementation that exposes CRUD methods for MAT.Entities.PlanillaServicio objects.
	///</summary>
	public abstract partial class WsPlanillaServicioProviderBase : PlanillaServicioProviderBase
	{
		#region Declarations	
	
		/// <summary>
		/// the Url of the webservice.
		/// </summary>
		private string url;
			
		#endregion Declarations
		
		#region Constructors
	
		/// <summary>
		/// Creates a new <see cref="WsPlanillaServicioProviderBase"/> instance.
		/// Uses connection string to connect to datasource.
		/// </summary>
		public WsPlanillaServicioProviderBase()
		{		
		}
		
		/// <summary>
		/// Creates a new <see cref="WsPlanillaServicioProviderBase"/> instance.
		/// Uses connection string to connect to datasource.
		/// </summary>
		/// <param name="url">The url to the nettiers webservice.</param>
		public WsPlanillaServicioProviderBase(string url)
		{
			this.Url = url;
		}
			
		#endregion Constructors
		
		#region Url
		///<summary>
		/// Current URL for webservice endpoint. 
		///</summary>
		public string Url
        {
        	get {return url;}
        	set {url = value;}
        }
		#endregion 
		
		#region Convertion utility
		
		/// <summary>
		/// Convert a collection from the ws proxy to a nettiers collection.
		/// </summary>
		public static MAT.Entities.TList<PlanillaServicio> Convert(WsProxy.PlanillaServicio[] items)
		{
			MAT.Entities.TList<PlanillaServicio> outItems = new MAT.Entities.TList<PlanillaServicio>();
			foreach(WsProxy.PlanillaServicio item in items)
			{
				outItems.Add(Convert(item));
			}
			return outItems;
		}
		
		/// <summary>
		/// Convert a nettiers collection to the ws proxy collection.
		/// </summary>
		public static MAT.Entities.PlanillaServicio Convert(WsProxy.PlanillaServicio item)
		{	
			MAT.Entities.PlanillaServicio outItem = item == null ? null : new MAT.Entities.PlanillaServicio();
			Convert(outItem, item);					
			return outItem;
		}
		
		/// <summary>
		/// Convert a nettiers collection to the ws proxy collection.
		/// </summary>
		public static MAT.Entities.PlanillaServicio Convert(MAT.Entities.PlanillaServicio outItem , WsProxy.PlanillaServicio item)
		{	
			if (item != null && outItem != null)
			{
				outItem.PlanillaServicioId = item.PlanillaServicioId;
				outItem.ViajeId = item.ViajeId;
				outItem.FechaRegistro = item.FechaRegistro;
				outItem.Total = item.Total;
				
				outItem.OriginalPlanillaServicioId = item.PlanillaServicioId;
				outItem.AcceptChanges();			
			}
							
			return outItem;
		}
		
		/// <summary>
		/// Convert a nettiers entity to the ws proxy entity.
		/// </summary>
		public static WsProxy.PlanillaServicio Convert(MAT.Entities.PlanillaServicio item)
		{			
			WsProxy.PlanillaServicio outItem = new WsProxy.PlanillaServicio();			
			outItem.PlanillaServicioId = item.PlanillaServicioId;
			outItem.ViajeId = item.ViajeId;
			outItem.FechaRegistro = item.FechaRegistro;
			outItem.Total = item.Total;

			outItem.OriginalPlanillaServicioId = item.OriginalPlanillaServicioId;
							
			return outItem;
		}
		
		/// <summary>
		/// Convert a collection from  to a nettiers collection to a the ws proxy collection.
		/// </summary>
		public static WsProxy.PlanillaServicio[] Convert(MAT.Entities.TList<PlanillaServicio> items)
		{
			WsProxy.PlanillaServicio[] outItems = new WsProxy.PlanillaServicio[items.Count];
			int count = 0;
		
			foreach (MAT.Entities.PlanillaServicio item in items)
			{
				outItems[count++] = Convert(item);
			}
			return outItems;
		}

		
		#endregion
		
		#region Get from  Many To Many Relationship Functions
		#endregion	
		
		
		#region Delete Methods
			
			/// <summary>
			/// 	Deletes a row from the DataSource.
			/// </summary>
			/// <param name="_planillaServicioId">. Primary Key.</param>	
            
			/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
			/// <remarks>Deletes based on primary key(s).</remarks>
			/// <returns>Returns true if operation suceeded.</returns>
			public override bool Delete(TransactionManager transactionManager, System.Guid _planillaServicioId)
			{
				try
				{
				// call the proxy
				WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
				proxy.Url = Url;
				
				bool result = proxy.PlanillaServicioProvider_Delete(_planillaServicioId);				
				return result;
				}
				catch(SoapException soex)
				{
					System.Diagnostics.Debug.WriteLine(soex);
					throw soex;
				}
				catch(Exception ex)
				{
					System.Diagnostics.Debug.WriteLine(ex);
					throw ex;
				}
			}
			
			#endregion Delete Methods
	
		
		#region Find Methods
		
		
		/// <summary>
		/// 	Returns rows meeting the whereclause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pagelen">Number of rows to return.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <remarks>Operators must be capitalized (OR, AND)</remarks>
		/// <returns>Returns a typed collection of MAT.Entities.PlanillaServicio objects.</returns>
		public override MAT.Entities.TList<PlanillaServicio> Find(TransactionManager transactionManager, string whereClause, int start, int pagelen, out int count)
		{
			try
			{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			
			WsProxy.PlanillaServicio[] items = proxy.PlanillaServicioProvider_Find(whereClause, start, pagelen, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Find Methods
		
		
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>			
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of MAT.Entities.PlanillaServicio objects.</returns>
		public override MAT.Entities.TList<PlanillaServicio> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
				
			WsProxy.PlanillaServicio[] items = proxy.PlanillaServicioProvider_GetAll(start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion GetAll Methods
		
		#region GetPaged Methods
						
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of MAT.Entities.PlanillaServicio objects.</returns>
		public override MAT.Entities.TList<PlanillaServicio> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			try
			{
			whereClause = whereClause ?? string.Empty;
			orderBy = orderBy ?? string.Empty;
			
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			
			WsProxy.PlanillaServicio[] items = proxy.PlanillaServicioProvider_GetPaged(whereClause, orderBy, start, pageLength, out count);
			
			// Create a collection and fill it with the dataset
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion GetPaged Methods
	
		
		#region Get By Foreign Key Functions
		#endregion
		
		
		#region Get By Index Functions
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_PlanillaServicio index.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="_planillaServicioId"></param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="count">out parameter to get total records for query</param>	
		/// <remarks></remarks>
		/// <returns>Returns an instance of the <see cref="MAT.Entities.PlanillaServicio"/> class.</returns>
		public override MAT.Entities.PlanillaServicio GetByPlanillaServicioId(TransactionManager transactionManager, System.Guid _planillaServicioId, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			WsProxy.PlanillaServicio items = proxy.PlanillaServicioProvider_GetByPlanillaServicioId(_planillaServicioId, start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Get By Index Functions
	
	
		#region Insert Methods
		/// <summary>
		/// 	Inserts a MAT.Entities.PlanillaServicio object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">MAT.Entities.PlanillaServicio object to insert.</param>		
		/// <remarks></remarks>		
		/// <returns>Returns true if operation is successful.</returns>
		public override bool Insert(TransactionManager transactionManager, MAT.Entities.PlanillaServicio entity)
		{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			
			try
			{
				WsProxy.PlanillaServicio result = proxy.PlanillaServicioProvider_Insert(Convert(entity));
				Convert(entity, result);
				return true;
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
	
		/// <summary>
		/// Lets you efficiently bulk many entity to the database.
		/// </summary>
		/// <param name="transactionManager">NOTE: The transaction manager should be null for the web service client implementation.</param>
		/// <param name="entityList">The entities.</param>
		/// <remarks>
		/// After inserting into the datasource, the MAT.Entities.PlanillaServicio object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		public override void BulkInsert(TransactionManager transactionManager, MAT.Entities.TList<PlanillaServicio> entityList)
		{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			try
			{
				proxy.PlanillaServicioProvider_BulkInsert(Convert(entityList));
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch (Exception ex)
			{	
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}

		#endregion Insert Methods
	
	
		#region Update Methods
						
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">MAT.Entities.PlanillaServicio object to update.</param>		
		/// <remarks></remarks>
		/// <returns>Returns true if operation is successful.</returns>
		public override bool Update(TransactionManager transactionManager, MAT.Entities.PlanillaServicio entity)
		{
			WsProxy.MAT.WebServices proxy = new WsProxy.MAT.WebServices();
			proxy.Url = Url;
			
			try
			{
				WsProxy.PlanillaServicio result = proxy.PlanillaServicioProvider_Update(Convert(entity));
				Convert(entity, result);
				entity.AcceptChanges();
				return true;
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Update Methods
			
		#region Custom Methods
		
		
		#endregion
					
	}//end class
} // end namespace
