/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file MAT.Entities.Servicio.cs instead.
*/

#region Using directives

using System;
using System.Data;
using System.Collections;
using System.Diagnostics;
using System.Web.Services.Protocols;
using MAT.Entities;
using MAT.Data.Bases;

#endregion

namespace MAT.Data.WebServiceClient
{

	///<summary>
	/// This class is the webservice client implementation that exposes CRUD methods for MAT.Entities.Servicio objects.
	///</summary>
	public abstract partial class WsServicioProviderBase : ServicioProviderBase
	{
		#region Declarations	
	
		/// <summary>
		/// the Url of the webservice.
		/// </summary>
		private string url;
			
		#endregion Declarations
		
		#region Constructors
	
		/// <summary>
		/// Creates a new <see cref="WsServicioProviderBase"/> instance.
		/// Uses connection string to connect to datasource.
		/// </summary>
		public WsServicioProviderBase()
		{		
		}
		
		/// <summary>
		/// Creates a new <see cref="WsServicioProviderBase"/> instance.
		/// Uses connection string to connect to datasource.
		/// </summary>
		/// <param name="url">The url to the nettiers webservice.</param>
		public WsServicioProviderBase(string url)
		{
			this.Url = url;
		}
			
		#endregion Constructors
		
		#region Url
		///<summary>
		/// Current URL for webservice endpoint. 
		///</summary>
		public string Url
        {
        	get {return url;}
        	set {url = value;}
        }
		#endregion 
		
		#region Convertion utility
		
		/// <summary>
		/// Convert a collection from the ws proxy to a nettiers collection.
		/// </summary>
		public static MAT.Entities.TList<Servicio> Convert(WsProxy.Servicio[] items)
		{
			MAT.Entities.TList<Servicio> outItems = new MAT.Entities.TList<Servicio>();
			foreach(WsProxy.Servicio item in items)
			{
				outItems.Add(Convert(item));
			}
			return outItems;
		}
		
		/// <summary>
		/// Convert a nettiers collection to the ws proxy collection.
		/// </summary>
		public static MAT.Entities.Servicio Convert(WsProxy.Servicio item)
		{	
			MAT.Entities.Servicio outItem = item == null ? null : new MAT.Entities.Servicio();
			Convert(outItem, item);					
			return outItem;
		}
		
		/// <summary>
		/// Convert a nettiers collection to the ws proxy collection.
		/// </summary>
		public static MAT.Entities.Servicio Convert(MAT.Entities.Servicio outItem , WsProxy.Servicio item)
		{	
			if (item != null && outItem != null)
			{
				outItem.ServicioId = item.ServicioId;
				outItem.Descripcion = item.Descripcion;
				outItem.Precio = item.Precio;
				outItem.Moneda = item.Moneda;
				outItem.Iva = item.Iva;
				outItem.Alicuota = item.Alicuota;
				outItem.Validez = item.Validez;
				outItem.VisibilidadTarifa = item.VisibilidadTarifa;
				outItem.ProveedorId = item.ProveedorId;
				outItem.TransporteId = item.TransporteId;
				outItem.HotelId = item.HotelId;
				outItem.TipoServicio = item.TipoServicio;
				
				outItem.OriginalServicioId = item.ServicioId;
				outItem.AcceptChanges();			
			}
							
			return outItem;
		}
		
		/// <summary>
		/// Convert a nettiers entity to the ws proxy entity.
		/// </summary>
		public static WsProxy.Servicio Convert(MAT.Entities.Servicio item)
		{			
			WsProxy.Servicio outItem = new WsProxy.Servicio();			
			outItem.ServicioId = item.ServicioId;
			outItem.Descripcion = item.Descripcion;
			outItem.Precio = item.Precio;
			outItem.Moneda = item.Moneda;
			outItem.Iva = item.Iva;
			outItem.Alicuota = item.Alicuota;
			outItem.Validez = item.Validez;
			outItem.VisibilidadTarifa = item.VisibilidadTarifa;
			outItem.ProveedorId = item.ProveedorId;
			outItem.TransporteId = item.TransporteId;
			outItem.HotelId = item.HotelId;
			outItem.TipoServicio = item.TipoServicio;

			outItem.OriginalServicioId = item.OriginalServicioId;
							
			return outItem;
		}
		
		/// <summary>
		/// Convert a collection from  to a nettiers collection to a the ws proxy collection.
		/// </summary>
		public static WsProxy.Servicio[] Convert(MAT.Entities.TList<Servicio> items)
		{
			WsProxy.Servicio[] outItems = new WsProxy.Servicio[items.Count];
			int count = 0;
		
			foreach (MAT.Entities.Servicio item in items)
			{
				outItems[count++] = Convert(item);
			}
			return outItems;
		}

		
		#endregion
		
		#region Get from  Many To Many Relationship Functions
		#endregion	
		
		
		#region Delete Methods
			
			/// <summary>
			/// 	Deletes a row from the DataSource.
			/// </summary>
			/// <param name="_servicioId">. Primary Key.</param>	
            
			/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
			/// <remarks>Deletes based on primary key(s).</remarks>
			/// <returns>Returns true if operation suceeded.</returns>
			public override bool Delete(TransactionManager transactionManager, System.Guid _servicioId)
			{
				try
				{
				// call the proxy
				WsProxy.MATServices proxy = new WsProxy.MATServices();
				proxy.Url = Url;
				
				bool result = proxy.ServicioProvider_Delete(_servicioId);				
				return result;
				}
				catch(SoapException soex)
				{
					System.Diagnostics.Debug.WriteLine(soex);
					throw soex;
				}
				catch(Exception ex)
				{
					System.Diagnostics.Debug.WriteLine(ex);
					throw ex;
				}
			}
			
			#endregion Delete Methods
	
		
		#region Find Methods
		
		
		/// <summary>
		/// 	Returns rows meeting the whereclause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pagelen">Number of rows to return.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <remarks>Operators must be capitalized (OR, AND)</remarks>
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> Find(TransactionManager transactionManager, string whereClause, int start, int pagelen, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			
			WsProxy.Servicio[] items = proxy.ServicioProvider_Find(whereClause, start, pagelen, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Find Methods
		
		
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>			
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
				
			WsProxy.Servicio[] items = proxy.ServicioProvider_GetAll(start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion GetAll Methods
		
		#region GetPaged Methods
						
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			try
			{
			whereClause = whereClause ?? string.Empty;
			orderBy = orderBy ?? string.Empty;
			
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			
			WsProxy.Servicio[] items = proxy.ServicioProvider_GetPaged(whereClause, orderBy, start, pageLength, out count);
			
			// Create a collection and fill it with the dataset
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion GetPaged Methods
	
		
		#region Get By Foreign Key Functions
		
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_Servicio_Hotel key.
		///		FK_Servicio_Hotel Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_hotelId"></param>
		/// <param name="count">out parameter to get total records for query</param>	
		/// <remarks></remarks>		
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> GetByHotelId(TransactionManager transactionManager, System.Guid? _hotelId, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			WsProxy.Servicio[] items = proxy.ServicioProvider_GetByHotelId(_hotelId, start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
			
		
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_Servicio_Proveedor key.
		///		FK_Servicio_Proveedor Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_proveedorId"></param>
		/// <param name="count">out parameter to get total records for query</param>	
		/// <remarks></remarks>		
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> GetByProveedorId(TransactionManager transactionManager, System.Guid? _proveedorId, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			WsProxy.Servicio[] items = proxy.ServicioProvider_GetByProveedorId(_proveedorId, start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
			
		
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_Servicio_Transporte key.
		///		FK_Servicio_Transporte Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_transporteId"></param>
		/// <param name="count">out parameter to get total records for query</param>	
		/// <remarks></remarks>		
		/// <returns>Returns a typed collection of MAT.Entities.Servicio objects.</returns>
		public override MAT.Entities.TList<Servicio> GetByTransporteId(TransactionManager transactionManager, System.Guid? _transporteId, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			WsProxy.Servicio[] items = proxy.ServicioProvider_GetByTransporteId(_transporteId, start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
			
		#endregion
		
		
		#region Get By Index Functions
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_Servicio index.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="_servicioId"></param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="count">out parameter to get total records for query</param>	
		/// <remarks></remarks>
		/// <returns>Returns an instance of the <see cref="MAT.Entities.Servicio"/> class.</returns>
		public override MAT.Entities.Servicio GetByServicioId(TransactionManager transactionManager, System.Guid _servicioId, int start, int pageLength, out int count)
		{
			try
			{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			WsProxy.Servicio items = proxy.ServicioProvider_GetByServicioId(_servicioId, start, pageLength, out count);
			
			return Convert(items); 
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Get By Index Functions
	
	
		#region Insert Methods
		/// <summary>
		/// 	Inserts a MAT.Entities.Servicio object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">MAT.Entities.Servicio object to insert.</param>		
		/// <remarks></remarks>		
		/// <returns>Returns true if operation is successful.</returns>
		public override bool Insert(TransactionManager transactionManager, MAT.Entities.Servicio entity)
		{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			
			try
			{
				WsProxy.Servicio result = proxy.ServicioProvider_Insert(Convert(entity));
				Convert(entity, result);
				return true;
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
	
		/// <summary>
		/// Lets you efficiently bulk many entity to the database.
		/// </summary>
		/// <param name="transactionManager">NOTE: The transaction manager should be null for the web service client implementation.</param>
		/// <param name="entityList">The entities.</param>
		/// <remarks>
		/// After inserting into the datasource, the MAT.Entities.Servicio object will be updated
		/// to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		public override void BulkInsert(TransactionManager transactionManager, MAT.Entities.TList<Servicio> entityList)
		{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			try
			{
				proxy.ServicioProvider_BulkInsert(Convert(entityList));
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch (Exception ex)
			{	
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}

		#endregion Insert Methods
	
	
		#region Update Methods
						
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">MAT.Entities.Servicio object to update.</param>		
		/// <remarks></remarks>
		/// <returns>Returns true if operation is successful.</returns>
		public override bool Update(TransactionManager transactionManager, MAT.Entities.Servicio entity)
		{
			WsProxy.MATServices proxy = new WsProxy.MATServices();
			proxy.Url = Url;
			
			try
			{
				WsProxy.Servicio result = proxy.ServicioProvider_Update(Convert(entity));
				Convert(entity, result);
				entity.AcceptChanges();
				return true;
			}
			catch(SoapException soex)
			{
				System.Diagnostics.Debug.WriteLine(soex);
				throw soex;
			}
			catch(Exception ex)
			{
				System.Diagnostics.Debug.WriteLine(ex);
				throw ex;
			}
		}
		
		#endregion Update Methods
			
		#region Custom Methods
		
		
		#endregion
					
	}//end class
} // end namespace
